### ISSUE TITLE
Turbo works strangely (Linux)

### ISSUE THREAD

**Issue by duganchen** [rdanbrook/nestopia#103]
I've found that on Linux, Turbo works strangely. In Super Mario Bros., if I hold down Turbo-A to hop and then press a direction button on the gamepad, then the Turbo hopping is cancelled out, even if I keep holding down Turbo-A. I've also, strangely, done high jumps when I held down Turbo-A and then just pressed left and right on the gamepad.

I get the same behavior with a Dualshock 4 and with an Xbox One controller, both connected via USB to a box running version 3.17 of the kernel. And SDL 2.03.

**Comment by rdanbrook** [comment]
Can't reproduce.
