### ISSUE TITLE
Nestopia is not Windows LUA compliant

### ISSUE THREAD

**Issue by bunglegrind** [rdanbrook/nestopia#108]
The problem is that Nestopia config file is created in the same folder of the application: this would be okay for windows 95 or windows 98, but in Win XP/Vista/7/8 compliant applications the config file must be located in the user home directory. Application shouldn't write in their directory at all, only in the users' folders.

**Comment by SedrynTyros** [comment]
Well, for anyone who likes their installation to be portable having Nestopia keep the config file in the program folder is ideal.  So, hopefully that option will still be available in the new Windows build.

**Comment by rdanbrook** [comment]
I'm going to keep the config file in the program directory.

**Comment by bunglegrind** [comment]
well, and a command line switch to set the config file path?
