### ISSUE TITLE
Unusual fullscreen combination

### ISSUE THREAD

**Issue by someguy21** [rdanbrook/nestopia#111]
Hi,

took me a while to find the ctrl-F shortcut. Also it isn't declared in the menues.
I'd suggest ctrl-enter and/or specify the shortcut beside the menu option.

**Comment by rdanbrook** [comment]
The default keys are listed in README.unix, and actually it's not ctrl+F. It's just F. If you want to change it you can modify ~/.nestopia/input.conf, but at this point there is no way to deal with key combinations, just one key.
