### ISSUE TITLE
fatal error: archive.h: No such file or directory

### ISSUE THREAD

**Issue by andoruB** [rdanbrook/nestopia#114]
Getting this while trying to compile:

> c++ -O3 -g3 -Isource -Wno-write-strings -Wno-deprecated-declarations -DDATADIR=\"/usr/local
> /share/nestopia\" -D_GTK -I/usr/include/SDL2 -D_REENTRANT -pthread -I/usr/include/gtk-3.0 -I/usr
> /include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/i386-linux-gnu/dbus-
> 1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include
> /pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo 
> -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 
> -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include  -c source/unix
> /gtkui/gtkui_archive.cpp -o objs/unix/gtkui/gtkui_archive.o
> source/unix/gtkui/gtkui_archive.cpp:24:21: fatal error: archive.h: No such file or directory
>  #include <archive.h>
>                      ^
> compilation terminated.
> Makefile:363: recipe for target 'objs/unix/gtkui/gtkui_archive.o' failed
> make: *** [objs/unix/gtkui/gtkui_archive.o] Error 1

There were no compiling instructions and there's only a makefile available so I assume I've done everything right by just running "make".

**Comment by rdanbrook** [comment]
https://github.com/rdanbrook/nestopia/blob/master/README.unix

You need libarchive-dev, or the equivalent package for your distribution.

**Comment by andoruB** [comment]
Ah, didn't see the oddly named README files, sorry and thanks :D
