### ISSUE TITLE
High CPU usage when idle/paused

### ISSUE THREAD

**Issue by andoruB** [rdanbrook/nestopia#115]
Whenever I pause the emulation or I don't have any ROM loaded, one of the CPU cores jumps to 100% usage, and stays that way until I load a ROM.

**Comment by rdanbrook** [comment]
You're right, that is definitely a bug... I have fixed this bug before, so I should be able to fix it again soon, once I have some time to sit down and code.

**Comment by andoruB** [comment]
Thanks for fixing this issue :)
