### ISSUE TITLE
SNES files with nestopia

### ISSUE THREAD

**Issue by chillson** [rdanbrook/nestopia#116]
Hey,

I am new here so if I do anything wrong pls give me a note.

Yesterday I tried some snes emus and then found a disksys.rom image that injected in nestopia started to play snes games. Most failed after some time but secret of mana played really great. Is it possible to use it on more games, or is there another snes image I may use for broader application?
I enclose the disksys.rom image as well as a screenshot of a zelda version snes I ran for some minutes on nestopia. Just download the .sys.png file and rename for use.

Iam happy about any good news =)

yours
![link_nestopia](https://cloud.githubusercontent.com/assets/10523748/5732024/6841463a-9b8b-11e4-9c1f-ce3d7ebc9f0a.jpg)
![disksys rom](https://cloud.githubusercontent.com/assets/10523748/5732032/94c7d250-9b8b-11e4-9183-6a75f8dc645f.png)

**Comment by Oggom** [comment]
...you created a Github account just to post this?

**Comment by chillson** [comment]
I had worse ideas, whats the point?

Am 14.01.2015 um 01:24 schrieb Oggom:

**Comment by dragon2snow** [comment]
snes?
oh!my god

**Comment by rdanbrook** [comment]
This doesn't make any goddamn sense. Something good was being smoked by the looks of it.
