### ISSUE TITLE
N163 sample length limit fix

### ISSUE THREAD

**Issue by koitsu** [rdanbrook/nestopia#118]
Recently it was discussed on nesdev that Nestopia's N163 emulation doesn't support sample lengths larger than 32.  The N163 information at the time was incorrect (including on our nesdev wiki, which was updated in 2011 to reflect correct info).  Games like Rolling Thunder use lengths >32.

Thread: http://forums.nesdev.com/viewtopic.php?f=6&t=12326

Fixes:

https://github.com/rdanbrook/nestopia/blob/master/source/core/board/NstBoardNamcot163.cpp#L292

Change 0x20UL to 0x100UL

https://github.com/rdanbrook/nestopia/blob/master/source/core/board/NstBoardNamcot163.hpp#L84

Change 0x1C to 0xFC

**Comment by rdanbrook** [comment]
I'll make the change in the very near future.
