### ISSUE TITLE
Baseball Stars II selection screen glitch

### ISSUE THREAD

**Issue by joepogo** [rdanbrook/nestopia#120]
I have been doing some extensive testing on some of the games that run off MMC3. particularly games that have been or might have been affected by the burai fighter fix. If you run baseball stars II for nes everything is ok until you get to the selection screen, it glitches up for a minute and turns from grey to white. 

Seems like something needs to be tweaked in the burai fighter fix as before this fix was applied it did not do this. I used nesguide on youtube as a reference. Figured i would add this here for a documenting issues that are still apparent. I will do more testing on my own to make sure it is in fact the burai fighter issue. It is def something in ppu.cpp.

**Comment by dragon2snow** [comment]
Thanks for providing information.
Try to replace the 665 and 666 line replacement for NstPpu.cpp
if ((scroll.address & 0x001F) != 0x001F)
					scroll.address++;
				else
					scroll.address ^= (0x001F | 0x0400);
				if ((scroll.address & 0x7000) != (7U << 12))
				{
					scroll.address += (1U << 12);
				}

**Comment by joepogo** [comment]
Thanks Dragon2snow, can you provide a full cpp file so i can make sure i do this correctly?

**Comment by rdanbrook** [comment]
I'm going to implement this change in my own branch and test it, either tonight or after the weekend. I'll do some extensive testing and see if there are any impacts, as well as research the actual root cause to see if there's a better solution.

**Comment by joepogo** [comment]
Thanks rdanbrook, yea this used to work as intended before the changes with burai fighter i think, but something is causing it to act weird now. please let me know what you see and find in your testing. much love to the baked beans. lmao.

**Comment by rdanbrook** [comment]
It appears that dragon2snow is referencing a different codebase, without the Burai Fighter fix implemented. It will take some thinking to try throwing his code/solution into the current codebase.

**Comment by rdanbrook** [comment]
Nevermind, it looks like I misread something. I'm pushing the code change now, it appears not to break anything from first glance.

**Comment by dragon2snow** [comment]
https://github.com/dragon2snow/NestopiaPlus
