### ISSUE TITLE
Nestopia Doesn't Support Headerless ROMs

### ISSUE THREAD

**Issue by Buddybenj** [rdanbrook/nestopia#121]
As far as I know, Nestopia supports correcting iNES ROM headers, but doesn't support loading headerless ROMs (e.g. No-Intro ROM set).

Headerless ROM to test: https://drive.google.com/open?id=0B8rgKAMnFwxpREtzb1NmWmZHRlk&authuser=0

**Comment by dragon2snow** [comment]
Nestopia not support No-Intro not iNES Header‘s rom
this rom,is not iNes

**Comment by wyatt8740** [comment]
To put that in slightly better and more coherent english, Nestopia doesn't support ROM's without headers, such as ones in the no-intro sets. It only supports iNES ones.

While I actually think byuu got it right using XML and headerless ROM's, this isn't a "bug" as much as a wishlist item.

**Comment by rdanbrook** [comment]
I have no plans to support headerless roms.
