### ISSUE TITLE
Palette - request for more options in libretro core

### ISSUE THREAD

**Issue by SedrynTyros** [rdanbrook/nestopia#122]
Absent the ability to load custom color palettes for the Nestopia core in RetroArch, how about adding some more selections?  I'd really love to be able to use Nestopia in RetroArch but the current palette selections all show Purple hues where I believe they should be Blue.  Super Mario Bros. is the easiest way to see what I'm talking about.

I realize you can't add every palette that everyone would ask for, but would it be doable to add in some of the more common ones used by FCEUmm?  Heck, just being able to load the "asqrealc" palette in Nestopia would probably satisfy most people who are looking for the Blue hues to replace the Purple.  Whenever I use the Win32 Nestopia v1.46 emulator, I always use the FCEUX.pal from FCEUX v2.2.2.  Not being able to have a similar color scheme for Nestopia in RetroArch makes it nigh unusable.

**Comment by rdanbrook** [comment]
It's a possibility, I'll take a look at it when I get tired of/frustrated with working on the core.

**Comment by SedrynTyros** [comment]
Thank you!  And thank you for all the great work you've done on Nestopia Undead!

**Comment by SuperrSonic** [comment]
This would be great, I'm a user of the libretro port on Wii and I'm used to the Wii Virtual Console palette.

I added the Wii VC palette back in 2014 to the fceumm libretro core but some of the games in my collection only work correctly in Nestopia.
https://github.com/libretro/libretro-fceumm/commit/82d72faf8f3804940310723a826e42c8efb35cd1
Either way thanks for this great emu.

**Comment by joepogo** [comment]
Hey SuperrSonic thanks for adding this info, is there anywhere i can get a .pal file for this? Id love to try it out.

**Comment by SuperrSonic** [comment]
https://www.dropbox.com/s/9qk2cs5fer1jsk5/Wii_VC.pal?dl=0

**Comment by Awakened0** [comment]
Firebrandx made some really nice palettes that are supposed to be very faithful to what came out of the NES' composite out. Information about them and a link to the .pal files are on his page here: http://www.firebrandx.com/nespalette.html

I think they'd be a great addition as palette options in the core.

**Comment by SigmaVirus** [comment]
@Awakened0 

Agreed, I've been using Firebrandx's palette through puNES and it very faithful.

Definitely something I would like to see be added to the Nestopia core in Retroarch as an alternative to the existing palettes in the future.

**Comment by SigmaVirus** [comment]
If anyone feeling bold and want to take a look at this, got skills to add some new palettes then this is the places I found where they are (might be more though)

Libretro.cpp
https://github.com/libretro/nestopia/blob/master/libretro/libretro.cpp#L521

NstApiVideo.cpp
https://github.com/libretro/nestopia/blob/master/source/core/api/NstApiVideo.cpp#L229

I'd add Firebrandx's and the 3DS VC palette in a heartbeat if I knew how.

**Comment by Awakened0** [comment]
I tested the added palettes in the libretro port. They look great! Unsaturated-V5 is the one I'm using as my default now.

Thanks!

**Comment by SedrynTyros** [comment]
Don't suppose anyone has the knowledge and desire to add the asqrealc palette to the libretro port?

**Comment by SuperrSonic** [comment]
Added the 3DS VC and Wii VC palette, I'm not doing a pull request.
I also added the palette from Mother 1+2, named it the AGB palette even though it's not the same as the Classic NES Series. The edited [libretro.cpp](https://www.dropbox.com/s/efnkdyd8uppqmf4/PALETTES_libretro.cpp?dl=1)

**Comment by rdanbrook** [comment]
I won't be adding any more palettes in the same way this was done in the recent pull request. I'd prefer any useful palettes to be added directly to the core, and others to be loadable at runtime. I am going to move the palettes from the previous pull request into the core at some point too.

I really want to avoid adding bells and whistles to one port only. I also want to avoid feature bloat.

**Comment by rdanbrook** [comment]
Custom palette loading has been added to standalone and libretro ports. Just put custom.pal into the system directory for libretro, or into the config directory for standalone (~/.nestopia). Might make it easier to select custom palettes in the standalone version as things progress.

**Comment by SedrynTyros** [comment]
Thank you for this, rdanbrook.  Much appreciated!
