### ISSUE TITLE
(libretro) Bake in NstDatabase

### ISSUE THREAD

**Issue by Oggom** [rdanbrook/nestopia#123]
It's is more of a suggestion than an issue, but I think it would be a good idea to automatically compile in the NstDatabase file into the libretro core itself instead of having it required as a separate file.

This would mean the libretro port could "just work" without being dependent on another file and it prevents unnecessary issue reports by people who forgot to download the database file in the first place.

**Comment by rdanbrook** [comment]
It's a great idea. Now I need to figure out how to do it. Any ideas? Can't say I've baked in an XML file into anything before ;).

**Comment by Oggom** [comment]
That's a good question, my experience with XML files is rather limited. :P
Wouldn't it be possible to add an #include for it within the libretro makefile?

**Comment by rdanbrook** [comment]
Something tells me it can't be that simple. I could be wrong though, I will have to do some research to figure this one out.

**Comment by wyatt8740** [comment]
Might you want to look into how goodNES works?
I personally have no idea, but I am guessing it is entered as an array or struct, or something of that sort.

**Comment by wyatt8740** [comment]
one more thing - I just saw this when googling. http://www.linuxjournal.com/content/embedding-file-executable-aka-hello-world-version-5967

**Comment by rdanbrook** [comment]
This doesn't seem feasible. The real solution is to deprecate the XML database, which will happen one day if I keep at it.
