### ISSUE TITLE
FME-7 IRQ acknowledgement bug (with fix)

### ISSUE THREAD

**Issue by koitsu** [rdanbrook/nestopia#124]
FME-7 IRQ acknowledgement behaviour has recently been analysed by Tepples and determined to be incorrect on a lot of emulators, including Nestopia.  The patch for Nestopia is simple.  Details are below:

Summary: http://forums.nesdev.com/viewtopic.php?p=142263#p142263

Thread w/ full details: http://forums.nesdev.com/viewtopic.php?f=2&t=12436

Patch: http://forums.nesdev.com/viewtopic.php?p=142317#p142317

**Comment by rdanbrook** [comment]
Patched! Thanks for letting me know.
