### ISSUE TITLE
Default PAL Drawing Area Is Wrong

### ISSUE THREAD

**Issue by Buddybenj** [rdanbrook/nestopia#125]
The default is 1-239, but it should be 0-239.

EDIT: What I said may actually be wrong, feel free to close this if it's wrong.

**Comment by rdanbrook** [comment]
Where are you seeing this? In the legacy win32 gui? Or the source? I skimmed through the source last night after work and didn't find anything obvious.

**Comment by Buddybenj** [comment]
I see it in the video options. The reason I said I may be wrong is because somebody told be that it varies depending on your TV.

**Comment by rdanbrook** [comment]
Yeah, that depends on the TV. It's the same for NTSC, it varies widely.

**Comment by Buddybenj** [comment]
Makes sense, It just seems weird to me to draw everything except for the top line.
