### ISSUE TITLE
Request submapper support

### ISSUE THREAD

**Issue by dragon2snow** [rdanbrook/nestopia#126]
Request submapper support
^o^

**Comment by rdanbrook** [comment]
One day. NES 2.0 support is on my list of more ambitious things to add.
http://wiki.nesdev.com/w/index.php/NES_2.0

**Comment by rdanbrook** [comment]
dragon2snow, do you have roms that use the submapper bits in the header?

**Comment by rdanbrook** [comment]
http://wiki.nesdev.com/w/index.php/NES_2.0_submappers

I will implement as many of these as it makes sense to implement. If anyone has feedback, throw it my way.

**Comment by dragon2snow** [comment]
I have never released.,but nessie102a11 author Released submapper rom
