### ISSUE TITLE
Error: cannot quit the program with gtk interface

### ISSUE THREAD

**Issue by inozemcew** [rdanbrook/nestopia#127]
If the program built with gtk interface no quit is possible until game is loaded and started. It is because of such lines of code in _main.cpp_
```c
    while (!nst_quit) {
    #ifdef _GTK
        while (gtk_events_pending() || !playing) {
                   gtk_main_iteration_do(TRUE);
        }
```
While _playing == false_  only inner loop is executed, condition for leaving outer loop can't be checked.

**Comment by rdanbrook** [comment]
You're right, and I've known about this for a few weeks. Just haven't had time to fix it, but probably will in the coming days.
