### ISSUE TITLE
Requesting External Shader / Filter support

### ISSUE THREAD

**Issue by wyatt8740** [rdanbrook/nestopia#128]
Hi, I'm wondering how hard it would be to add bsnes-style shaders to nestopia. Something like these: https://github.com/hizzlekizzle/quark-shaders

or alternately, I'd also appreciate GLSL filters, RetroArch style. https://github.com/libretro/common-shaders

How much work would it be to implement something like this? It'd be a lot more convenient than re-compiling.

**Comment by rdanbrook** [comment]
It's going to require a rewrite of the OpenGL stuff. That is something I have planned for the near future, definitely before the next release gets tagged. Shouldn't be difficult, just a matter of me actually getting around to doing it.

**Comment by rdanbrook** [comment]
I'm closing this because it's essentially a duplicate.
