### ISSUE TITLE
GTK UI should have quick save state functionality in the menus.

### ISSUE THREAD

**Issue by wyatt8740** [rdanbrook/nestopia#129]
I know that via F5 and F7 (default, changed in input.conf) you can quick save save states, but I'd like to ask that there also be menu options for this.

**Comment by rdanbrook** [comment]
Eventually there will be menu options to change UI keys. Before I do it I want to rethink input as a whole though, because I want to support all of the exotic input devices the core supports.

**Comment by wyatt8740** [comment]
no, you misunderstand. I meant that in a menu at the top, in addition to saving states to files, there should be entries for quick state saving.

**Comment by rdanbrook** [comment]
Done.
