### ISSUE TITLE
Linux Fullscreen Flickering wildly

### ISSUE THREAD

**Issue by wyatt8740** [rdanbrook/nestopia#130]
I'm having the bug seen here with the latest git build of nestopia.
http://youtube.com/watch?v=LaUnTgTONJ8

My chipset is the Intel GMA 945.
I used the GTK build.
My chipset from lshw:
Mobile 945GM/GMS/GME, 943/940GML Express Integrated Graphics Controller

**Comment by rdanbrook** [comment]
I know what this problem is. On ATI/AMD and Nouveau it happens a little differently, but same bug. Shouldn't be hard to solve. The question is... do I fix this bug now, or do I just rewrite the OpenGL code to be "modern", which I'm going to do anyway?

**Comment by wyatt8740** [comment]
what is it doing wrong, then? I'm curious.

**Comment by rdanbrook** [comment]
I'll never support anything other than OpenGL, except maybe Vulkan if it ever seems worthwhile to do so. It's OpenGL or nothing. Keeping it simple means less potential issues, and less complexity in the codebase. Plus anything reliant on X is already obsolete, and not really cross-platform. SDL's software renderer is not worth dealing with.

What's happening is that the image is being blitted to a textured quad every frame. The non-textured area is simply not drawn to at all, and it causes all kinds of artifacts to show up with other drivers.

I'm going to get rid of the current OpenGL code and replace it with modern OpenGL rather than the current fixed function code.

**Comment by wyatt8740** [comment]
As long as opengl 2.x is still compatible, that'll be fine... :)

**Comment by rdanbrook** [comment]
It will be 3.0+. If your card doesn't support it, then you'll just fall back to software (Mesa) and it will be slower than hell, but that is the cost of progress :).

**Comment by wyatt8740** [comment]
D:
what if I ask you nicely to reconsider?

(but really, requiring openGL 3.0 kills a ton of hardware. one of my four computers supports OpenGL 3.0. The NES shouldn't require 3.0, should it?)

**Comment by rdanbrook** [comment]
Well, look at it this way... you have another issue posted here requesting shaders. That's not happening without OpenGL 3. Wayland support isn't happening without OpenGL 3 either. Neither is removing my terrible X11-only hack to make the OpenGL context embed in the window. So basically, OpenGL 2.0 and below are disappearing. Software implementations can handle it if your GPU hardware doesn't.

This is just how things work. I can't support old stuff forever. I also dropped official support for XP, and in the future I will not be supporting MS DOS, or any other ancient, obsolete technology ;).

**Comment by wyatt8740** [comment]
wait, it builds for DOS?

On a different note, I'd prefer that it continue to work with older *hardware*. Software I can deal with losing support... but I don't want a perfectly capable computer that can run the windows version fine to be locked out of the linux version because of high GPU requirements.

**Comment by wyatt8740** [comment]
As a temporary fix, you can use a compositing window manager (I used compton) and this fixes the flickering issue. Could that be added to the README or something?

**Comment by rdanbrook** [comment]
I already rewrote the OpenGL stuff to be modern. I'm just fixing up a few bugs before I push it.

**Comment by wyatt8740** [comment]
BTW, I figured out why mesa's software driver wasn't working for me. I had to set LIBGL_ALWAYS_SOFTWARE to make higan work, at least.

**Comment by rdanbrook** [comment]
Issue no longer exists after full rewrite.
