### ISSUE TITLE
[request] configuration dialogue should remember last open tab

### ISSUE THREAD

**Issue by wyatt8740** [rdanbrook/nestopia#132]
I think there should at least be an option to remember the last tab opened in the nestopia configuration dialogue.  If I am changing settings a lot, it's a hassle to change the tab every time I open the dialogue.

**Comment by rdanbrook** [comment]
It's not a big deal to do this. I can see the benefit so maybe I'll do it soon.

**Comment by wyatt8740** [comment]
thanks :)

**Comment by rdanbrook** [comment]
Done.

**Comment by wyatt8740** [comment]
awesome :)
