### ISSUE TITLE
 Tile replacement

### ISSUE THREAD

**Issue by ADormant** [rdanbrook/nestopia#133]
Hi, this is a very interesting feature, I wonder if it could be done in Nestopia? Currently among Nes emulators only HDNes is capable of doing it. https://github.com/mkwong98/HDNes Description http://www.1emulation.com/forums/files/file/23-hdnes/
![supermariohd3 hdnes](https://cloud.githubusercontent.com/assets/10523326/6929598/5684d29c-d7fc-11e4-9824-5673f8c33063.jpg)

**Comment by rdanbrook** [comment]
It could be done, but it would be a herculean effort. Nestopia is not really designed well to add gimmicks like this.

**Comment by ADormant** [comment]
I see, too bad because Nestopia has better compatibility than hdnes.
