### ISSUE TITLE
GTKUI Windows Port

### ISSUE THREAD

**Issue by DoctorWho11** [rdanbrook/nestopia#135]
Not so much of an Issue, more like a report and hopefully soon a pull request. Just was able to compile the gtkui on Windows. As you can see the SDL backend is rather... transparent and doesn't quick function well yet. I have AO disabled, though AO could be enabled though. But I figure I'd report my progress
![nestopiaue](https://cloud.githubusercontent.com/assets/8948676/6990765/19f1579a-da42-11e4-94e7-fd96d8915143.png)

**Comment by rdanbrook** [comment]
This is pretty cool, I'm surprised it even works this well. I'm surprised you even got it to compile, since it uses gdkx.h.

The reason this doesn't work is because it's trying to use an X11 callback to get the XID of the GtkDrawingarea to embed the OpenGL context into. The next version of GTK+ supports OpenGL natively, so it is potentially possible to build with a GTK+ GUI on Windows if I implement that. I'm not sure how well it will perform, because GTK+ on Windows has never been quite up to par.

Currently the Windows build should work fine if compiled without GTK+, and also compiled against a development version of SDL (SDL sound instead of libao, though you could use libao on Windows probably). I'm waiting for an official tagged release of SDL 2.0.4 to build my own alpha Windows binary.

**Comment by wyatt8740** [comment]
I have managed to compile the SDL port on mingw, and it runs slowly. But I too am suprised with the gtkui build! Good going!

**Comment by DoctorWho11** [comment]
Actually this is compiled against gtk 3.16 which is provided by msys2. But I basically changed the include to gdkwin32 and the gdk xid stuff was replaced with gdk hwnd

**Comment by wyatt8740** [comment]
So nothing is rendered in your build?
the SDL port did that when I compiled it again in cygwin.

**Comment by rdanbrook** [comment]
That's even cooler. I wouldn't mind seeing a diff, just to see what you did.

**Comment by wyatt8740** [comment]
I second that.

**Comment by DoctorWho11** [comment]
Lemme pull a clean source and make a diff

**Comment by DoctorWho11** [comment]
It's a dirty patch. Eventually I'll clean it up properly 
http://hastebin.com/dajuyatefu.diff

**Comment by rdanbrook** [comment]
Awesome, that's great information to know. However, what I will likely do is remove a lot of the embedding logic and do it properly, using the GTK+ OpenGL widget that works transparently across all windowing systems, including Wayland.

**Comment by DoctorWho11** [comment]
Well using gtkglarea (the gtk widget in 3.16) does support wayland iirc so using that would be beneficial. Right now the major pita at the moment is AO support, it has winmm support but it's broken in the latest version so I opted to just default to SDL for that. 

If you want I could see about adding the gtkglarea code

**Comment by rdanbrook** [comment]
To do that you'll have to rewrite a lot of the OpenGL code in video.cpp, since the widget is core profile only. If you're up for that feel free, but it's already on my list; probably the next thing I'll do. Maybe in the next few days.

**Comment by DoctorWho11** [comment]
Well since it's your project I'll probably wait until you get some initial work done and contribute. Probably better that way since it'd be your design specification and how you want it.

**Comment by wyatt8740** [comment]
Audio worked on my Cygwin SDL build but graphics didn't. I was using SDL audio.

**Comment by DoctorWho11** [comment]
@wyatt8740 I haven't used cygwin. This is native windows built using mingw

**Comment by wyatt8740** [comment]
updated my comment. (added 'for what it's worth').

Anyway, my cygwin build without GTK worked fine.

**Comment by wyatt8740** [comment]
(s/cygwin/mingw/)

**Comment by DoctorWho11** [comment]
the sdl build is not really trivial. I needed a challenge.

**Comment by wyatt8740** [comment]
I appreciate your dedication :) It'd be nice to have the same version available for every platform. And I could prove beware (developer of BGB) wrong about it being impossibly hard to use the same UI on windows and linux :)

**Comment by DoctorWho11** [comment]
Well it's not hard really. Toolkits like wxwidgets and now gtk (version 3.16) that have builtin gl interface widgets make it relatively easy to maintain. It's also a matter of using portable code and nothing operating system specific in your core programing.

**Comment by rdanbrook** [comment]
Closing this, because I'm not even sure I want to support GTK+ on Windows.
