### ISSUE TITLE
Newest nestopia build ignores filter settings when started with GUI.

### ISSUE THREAD

**Issue by wyatt8740** [rdanbrook/nestopia#136]
The bug is described in the title. The newest nestopia build ignores filter settings when started with GUI.

If run with nestopia -d (disable gui) it remembers and loads the filter from settings. if run with nestopia -e (or if nestopia.conf is edited manually to enable GUI), the filter is reset. Other things may be as well, but my initial testing noticed this.

**Comment by rdanbrook** [comment]
Can't reproduce.

Do you see any errors?

Can you use GDB to find out if it exits cleanly?

**Comment by wyatt8740** [comment]
my fault. bad regex in a script. I'll re-open if I learn otherwise. >.<
