### ISSUE TITLE
Method for tuning NTSC filter

### ISSUE THREAD

**Issue by wyatt8740** [rdanbrook/nestopia#137]
Nestopia for windows has an excellent dialog for tuning the NTSC filter:

![Screenshot of windows Nestopia's NTSC tuning UI](http://i.imgur.com/Otvpm49.png)

Something similar would be great to have here. I am going to try to hack it in, but I don't have any experience at all hacking GTK3, so I don't expect to get very far.

**Comment by rdanbrook** [comment]
This is really easy to do. It will require a few more config settings to be added, and I'll probably implement it at the config file level before it ever goes into the GUI. Reason being, I haven't thought of a way to make it not look like hell in the GUI yet.

**Comment by rdanbrook** [comment]
Okay, it's done but not fully implemented in the GUI. You can select to use the configuration file defined values in the GUI though, until I figure out how I want to do this in the GUI.
