### ISSUE TITLE
(libretro): Add force Region (NTSC/PAL/Dendy) selector

### ISSUE THREAD

**Issue by eugene-s-nesdev** [rdanbrook/nestopia#141]
Hi, Rdanbrook.

Please add region (NTSC/PAL/Dendy) selector to libretro core.
Dendy-mode was designed only for run actual NTSC-games at 50FPS
So, none of exclusive software\games was written special for dendy-mode and region detection (based on NstDatabase.xml) can't detect Dendy.

Thank You
Eugene.S (emu-russia)

**Comment by rdanbrook** [comment]
Will do soon, should be very simple.

**Comment by rdanbrook** [comment]
Done.
