### ISSUE TITLE
(libretro) lastest favored system selector.

### ISSUE THREAD

**Issue by eugene-s-nesdev** [rdanbrook/nestopia#143]
Hi, Rdanbrook. I've updated libretro core today, and seems region selector doesn't work.
I try to set force PAL and Dendy modes, but emulator still work on NTSC even after restart.

Try to test this timing ROM: 
http://forums.nesdev.com/viewtopic.php?f=22&t=12499#p143056

How it must look in all 3 modes:
http://savepic.ru/7604789.png
![overclock_png](https://cloud.githubusercontent.com/assets/13199529/8929553/0bfa1508-352f-11e5-9808-dace1956dd1c.png)

**Comment by rdanbrook** [comment]
It works for Dendy for me, but not PAL... that's strange. I'll take another look at it soon. It also does not work in PAL mode on the cross-platform standalone build either.

Thanks for pointing out this test rom, it makes life a lot easier.

**Comment by eugene-s-nesdev** [comment]
So strange. I've updated libretro core just now.
PAL is working, but Dendy doesn't (and run like NTSC)

Here is config: (retroarch-core-options.cfg)

1. for PAL:
nestopia_blargg_ntsc_filter = "rgb"
nestopia_palette = "consumer"
nestopia_nospritelimit = "disabled"
nestopia_fds_auto_insert = "enabled"
nestopia_overscan_v = "enabled"
nestopia_overscan_h = "disabled"
nes_palette = "asqrealc"
nestopia_genie_distortion = "disabled"
nestopia_favored_system = "pal"

2. for Dendy:
nestopia_blargg_ntsc_filter = "rgb"
nestopia_palette = "consumer"
nestopia_nospritelimit = "disabled"
nestopia_fds_auto_insert = "enabled"
nestopia_overscan_v = "enabled"
nestopia_overscan_h = "disabled"
nes_palette = "asqrealc"
nestopia_genie_distortion = "disabled"
nestopia_favored_system = "dendy"

**Comment by rdanbrook** [comment]
Try disabling the database and see what happens. If the database is present and the rom is not detected, it isn't setting the system based on the core option. I didn't have time to complete this last night, maybe tonight I will.

**Comment by rdanbrook** [comment]
Alright, it now works exactly the same as the Windows version, which I might add is very confusing. 

Setting "dendy" at the beginning will make "auto", "pal" and "dendy" show the results in the image you showed for Dendy until the next time the program is started.

Setting "pal" will make both "pal" and "dendy" show the results you showed for PAL until the next time the program is started.

Setting "auto" or "ntsc" will make PAL and Dendy work like PAL. Note that in the original Windows version there is no option to force Dendy mode.

Setting "ntsc" will make "auto" behave like NTSC, and PAL and Dendy behave like PAL.

This is far more confusing than it should be, but the reality is that in the core this doesn't really make sense.

If you have anything to add, feel free to fill me in. I have never used a PAL console or a Dendy in real life so there might be something I'm missing.

**Comment by eugene-s-nesdev** [comment]
Damn, Martin made very complicated and uncomfortable selectors:
1) options -> preferences -> favored system
2) machine -> region

If "favored system"=dendy, and "region"=PAL -> we have force Dendy mode in Windows version.

**Comment by eugene-s-nesdev** [comment]
I've just updated libretro core and confused too.
Emulator save region status after restart program.
But sound is completely broken on NTSC and Dendy, on PAL it work good.

**Comment by rdanbrook** [comment]
What roms are you testing it on? Sound was fine for me on NTSC games using NTSC mode.

Yes, I agree that this is confusing and I think I may rearchitect it at the core level to make more sense. I think I may save this until I have deprecated the original win32 version though, because I really don't want to touch that mess ever again.

**Comment by eugene-s-nesdev** [comment]
You can test regions on "Battletoads and Double Dragon (USA)". 
It good test rom for it.

On NTSC it work perfect
On Dendy it work with minor glitches: 
http://hwm.us.to/famimusic/Forum/hardware_tests/game_glitches/Battletoads%20Double%20Dragon.gif
On PAL it work with strong glitches at title and hangs in-game

**Comment by eugene-s-nesdev** [comment]
Also, here is my old issue (i am emu-russia):
https://github.com/rdanbrook/nestopia/issues/46
http://forums.nesdev.com/viewtopic.php?p=113012#p113012

You can read my nesdev post:
Dendy inaccuracy happened after Martin did "favored system" in 1.38.

**Comment by eugene-s-nesdev** [comment]
You are right, current region selector in Windows is completely bad.
User cannot enable or disable Dendy-mode without exit/start emulator but can change between NTSC PAL on-the-fly.
*****
You can test regions on "Battletoads and Double Dragon (USA)". 
It good test rom for it.
On NTSC it work perfect (at 60FPS)
On Dendy it work (at 50FPS) with minor glitches: 
http://hwm.us.to/famimusic/Forum/hardware_tests/game_glitches/Battletoads%20Double%20Dragon.gif
On PAL it work (at 50FPS) with strong glitches on title and hangs in-game
*****
Also, here is my old issue (i am emu-russia): https://github.com/rdanbrook/nestopia/issues/46
http://forums.nesdev.com/viewtopic.php?p=113012#p113012

You can read my nesdev post:
Dendy inaccuracy happened after Martin did "favored system" in 1.38

**Comment by emu-russia** [comment]
Well, i've just tried on lakka with lastest 1.48 core.
First of all:
Region changing will not work correct until you reboot nestopia core, otherwise you'll get completely mess of bugs like https://github.com/rdanbrook/nestopia/issues/143#issuecomment-126163280.
Dendy mode work incorrect even after core reboot: FPS-meter really snows 60 FPS instead of 50, despite gamespeed and sound tempo looks like on 50 FPS. I'm suggesting this cause sound skipping problems.

Strange that sound was also broken on NTSC too, when i tried it on windows last time.
https://github.com/rdanbrook/nestopia/issues/143#issuecomment-126411201

**Comment by emu-russia** [comment]
****NOTE****
Original nestopia for windows has uncomfortable region selector. 
You have only "Auto/NTSC/PAL" switch instead of "Auto/NTSC/PAL/Dendy" which looks more logical. 
If you want to set dendy mode, go to preferences and select dendy in "favored system" settings.
Then you need to close emulator. After start it again, PAL mode in region selector will work like dendy. 
If you need to get PAL backward, you do the full cycle all over again. 
It's really uncomfortable trash.
********

**Comment by eugene-s-nesdev** [comment]
Something strange happens with https://github.com/rdanbrook/nestopia/issues/46
There was buggy audiosync topic.
[1.46.2_Dendy_Mode_Timing_Fix.zip](https://github.com/rdanbrook/nestopia/files/308865/1.46.2_Dendy_Mode_Timing_Fix.zip)

After 2 days of HARD debugging, FHorse has FIXED all those bugs in dendy mode. 
http://savepic.ru/7682327.png
Now all works like charm
Source of problem was the flag of VBLANK and the NMI were set prior of sleep scanlines (in new part of code that was added since 1.38)
Here is the patch FHorse did for 1.46.2, because you've dropped out all lower than OpenGL 3.2 since 1.47 (i see only black screen on i7-2600K/GMA HD3000, that has OGL3.1 only, why you did it ???)

Can you also disable these 2 lines in NstApu.cpp to do triangle fix in dendy mode right way?
http://savepic.su/7245317.png

https://github.com/rdanbrook/nestopia/blob/master/source/core/NstApu.cpp
Lastest source shows me it 1595 and 1596 lines for now.

Also i have a request about region selectors. For now it completely broken.
Original Nestopia has 2 region selectors. 
First was main, named "Region selector", which contain "auto/NTSC/PAL" modes, and it was able to FORCE select mode.
Second was slave, named "Favored system", which contain "NES NTSC / NES PAL / Famicom and Dendy" modes, and it parameters were linked to main selector.
For example, 
If you want to set dendy mode, go to preferences and select dendy in "favored system" settings.
Then you need to close emulator. After start it again, PAL mode in region selector will work like dendy.
If you need to return PAL back, you do the full cycle all over again. 

But you're kicked out MAIN Region selector since 1.46 in linux version, and for now we got strange behaviour things.
On my machine all "NES NTSC / NES PAL / Famicom and Dendy" works like NTSC
On FHorse machine only NTSC and Dendy works, but he cannot get true PAL.
We tried vanilla 1.46.2, of course, with Tepples's overclock demo, that i've linked here:
https://github.com/rdanbrook/nestopia/issues/143

This is awful.

**Comment by eugene-s-nesdev** [comment]
I've just compiled lastest nestopia-master branch on Xubuntu 14.04.
I'm glad to report - dendy fix by FHorse works like a charm, all timings correct for now!
Thank you very much for apply all patches we asked.

Rdanbrook, it's very sad but seems selectors are cursed again. All works as last time...
I've listened music speed of NTSC-games (don't see picture because Intel GMA HD3000 lacks OpenGL 3.2)
and all of them sound on NTSC speed in all modes (NTSC\PAL\Dendy).
When i've tried 1.46.2 last time (it shows picture on my machine) there was same bug.
All of "NES NTSC / NES PAL / Famicom and Dendy" works like NTSC, and i noticed this via tepples timing ROM.

Then i've downloaded lastest retroarch core. I've checked it fresh because all dendy timings works correct now.
And i've got same problem as last time.
https://github.com/rdanbrook/nestopia/issues/143#issuecomment-223729909
NTSC and PAL works good, but Dendy framerate is 60FPS instead of PAL, but it sounds on 50FPS, that cause skipping sound fragments.

On the windows port, which still have old 2 selectors ALL work good.

Maybe better to use game for test instead of tepples overclock rom, because you can see gamespeed and listen sound tempo real time.
As i've already said, you can test regions on "Battletoads and Double Dragon (USA)".
It's very good test rom for it.
On NTSC it work perfect at 60FPS
On Dendy it work at 50FPS (including 50FPS sound tempo) with minor glitches:
http://hwm.us.to/famimusic/Forum/hardware_tests/game_glitches/Battletoads%20Double%20Dragon.gif
On PAL it work at 50FPS (including 50FPS sound tempo) with strong glitches on title and hangs in-game.

**Comment by rdanbrook** [comment]
I just fixed this problem. It appears to work correctly on the test rom, as well as Battletoads-Double Dragon.

**Comment by eugene-s-nesdev** [comment]
Yes, it work correct now. Thank you. Seems libretro-port is fixed.
I hope you'll can fix cross-platform port too.

**Comment by rdanbrook** [comment]
I fixed the selector on the cross-platform port as well, I can't reproduce any problems now.
