### ISSUE TITLE
Startropics modification support

### ISSUE THREAD

**Issue by bbbradsmith** [rdanbrook/nestopia#144]
Nestopia seems to identify Startropics by CRC, which selects an MMC6 implementation instead of MMC3 for Mapper 4. (Both were assigned to the same iNES number.)

Because of this, romhacks/modifications of Startropics (or its sequel) are unplayable on Nestopia. I noticed this when I recently created a bug-fix patch for it:
http://www.romhacking.net/hacks/2229/

There are a few options:

1. Add CRCs of patched versions as you find them. My patch is two CRCs (U and E versions), but I have no idea how many other Startropics hacks there might be out there. RHDN doesn't have any others.

2. Alternative implementation of mapper 4. Remove the functionality of $A001 and the MMC3 mapper becomes compatible with MMC6. Detect Low G Man by CRC instead of Startropics to enable the functionality of $A001 and its ability to disable and open-bus the PRG-RAM area (Low G Man is the only game that needs this). This, of course, shifts the problem from Startropics to Low G Man. This way Low G Man doesn't support romhacks, unless those hacks fix the bug that relies on open-bus behaviour. :( This also might break saved games if they expect to load/save a 1K SRAM file for Startropics. Could be a bit tricky.

Info: http://wiki.nesdev.com/w/index.php/MMC3#iNES_Mapper_004_and_MMC6

3. iNES 2.0 support? This doesn't help much, since basically only homebrew uses the new headers and old ROM sets are probably never going to be updated. Low G Man could use iNES 2 to specify no PRG-RAM. Startropics can use iNES 2 to specify 1k PRG-RAM for MMC6 (or IMO, MMC6 should be a selectable submapper, currently arbitrating this over at NesDev). It seems impractical to expect this to ever be useful for old ROMs, but at least it could potentially help with new hacks or homebrew.

So, I mean, probably the lowest impact thing is to add the two CRCs for my patch. Even lower impact is to ignore this request entirely. ;) I couldn't find any other Startropics romhacks besides mine anyway, so maybe it's not much of an issue,

**Comment by rdanbrook** [comment]
https://github.com/rdanbrook/nestopia/commit/deebbc52888e0bc3f147c767543b7f079d306145

This is the NES 2.0 solution.

I am actually hoping to release a romset with NES 2.0 headers, probably beginning with only games that actually benefit from this.

I'm not really excited about adding more hash values to the database for every hack that comes out.

**Comment by bbbradsmith** [comment]
Ah, actually that looks straightforward! OK!

The only problem is that MMC6 was never assigned a submapper (which is bizarre... because I thought it was the single most important reason for NES 2.0 to exist). I've tentatively allocated it as submapper 4, but I've got to hash it out with tepples and the nesdev crowd.

**Comment by rdanbrook** [comment]
http://wiki.nesdev.com/w/index.php/NES_2.0_submappers#004:_MMC3

According to this it is drafted as submapper 4. I guess I should change my source code. I have been going from:
http://blog.kevtris.org/blogfiles/nes/submappers.txt

I guess all of us need to push for some standardization of these submappers before anything can really move forward.

**Comment by bbbradsmith** [comment]
I'm the one that added it as submapper 4 earlier today. :P After looking into this more I'm realizing what an awful state the wiki's version of things is in. I've reopened an old thread about it on the nesdev forums. If you've got an opinion on the matter I'm sure another voice would be welcome:
http://forums.nesdev.com/viewtopic.php?f=3&t=9350

**Comment by dragon2snow** [comment]
Hip, hip, hurray

**Comment by bbbradsmith** [comment]
I spent some time going over the NESDev wiki spec for NES 2.0 today. Hopefully this version is a lot clearer:
http://wiki.nesdev.com/w/index.php/NES_2.0_submappers

Tepples put MMC6 back as submapper 1 for mapper 4, so... possibly this issue is already resolved. :> Hopefully we can keep the specification clean going forward, and hopefully existing numbers stop moving around. D:<

**Comment by bbbradsmith** [comment]
I tried building Nestopia UE and testing it, interestingly my version with the iNES 2 header works fine now, the original Startropics apparently doesn't. (Did you remove CRC tests entirely?)

Not sure if the version I'm running is in a weird state, it was just the master branch, and the only thing I could find in there to build was the libretro DLL version, which is how I tested this.

**Comment by bbbradsmith** [comment]
Closing it, because I guess it was supported all along! I think the NES 2.0 submapper specification has stabilized too after some discussion. I think what's left on the wiki now is much more implementable.

**Comment by rdanbrook** [comment]
If there is no database entry, it will look at the header, but the database does take precedence. I'm hoping that one day I can deprecate the database, but that's probably a long way off. I think NES 2.0 is the way to go moving forward, and my eventual plans to release a romset will hopefully help the situation.
