### ISSUE TITLE
xBRZ Filter

### ISSUE THREAD

**Issue by Papermanzero** [rdanbrook/nestopia#145]
Currently Nestopia only supports xBR.
However due to some small pixel arts, it is recommended to use xBRZ (xBR ignores the original pixel lines and scales the graphics not accurate. Sometimes it mixes pixels together). Look at this screenshot: http://i.imgur.com/k2IZVjp.png

xBRZ is using the same basic idea of Hyllian's xBR of a rule-based scaler, but has been written completely from scratch in C++ with different rules and the goal of fully supporting multi-core CPUs as well as a few other visual enhancements. The biggest advantage compared to standad scalers like HQx are less washed-out (background) textures and less pixelation in general.

source: http://sourceforge.net/projects/xbrz/files/HqMAME/

**Comment by DonelBueno** [comment]
I support this change. The xBR filter in nestopia is an old version of xBR itself, so the difference when compared to xBRZ is pretty big.

**Comment by rdanbrook** [comment]
I don't realistically have time to port this, if someone else wants to, I am accepting pull requests.
