### ISSUE TITLE
Request: MultiTap Support

### ISSUE THREAD

**Issue by newoski** [rdanbrook/nestopia#146]
Sorry. Meant to post this on the RetroArch core github

**Comment by rdanbrook** [comment]
Yes, I can add this feature to the libretro port. I am very busy lately, but it shouldn't be too hard to get it done.

**Comment by newoski** [comment]
Thank you so much!!! Any idea what would be a realistic time to completion? So excited!

**Comment by rdanbrook** [comment]
Now you can play "A Nightmare on Elm Street" in 4-player mode.

**Comment by newoski** [comment]
Thanks so luck! Assuming this works for all MultiTap games, not just Elm Street? Also, how is enabled? Core settings or input settings?

**Comment by rdanbrook** [comment]
It will work with any 4-player game (or 3-player). If the XML database is present it will select inputs based on that, otherwise it will default to 4 regular pads plugged in. You'll just need to configure the inputs for the extra pads in RetroArch or whatever other frontend you may be using.

**Comment by newoski** [comment]
One more question... Where do I get the XML database you refer to?

**Comment by rdanbrook** [comment]
https://github.com/rdanbrook/nestopia/blob/master/NstDatabase.xml

**Comment by newoski** [comment]
Thanks so much, it's working perfectly!!!
