### ISSUE TITLE
How to compile in Windows ?

### ISSUE THREAD

**Issue by steelywing** [rdanbrook/nestopia#154]
Could you make a guide about compile this in Windows pls? I only can compile this in Linux. :cry:

**Comment by rdanbrook** [comment]
It depends on what you're trying to compile.

If you want to compile the old, crufty original win32 port, clone this: https://github.com/rdanbrook/nestopia-win32

And then overlay it on top of the sources from this repo, and open up the .sln from Visual Studio 2010.

If you want to compile the sources from this repo, and use the port I've been working on for the last 3 years, you will need MinGW. I'm using MSYS2: https://msys2.github.io/

The MinGW build is not release quality yet, but it will be usable as a standalone command line application with full features as soon as SDL 2.0.4 is released, or if you build your own SDL libs from hg.

**Comment by steelywing** [comment]
Thanks, I want to try the old win32 port, look like simpler for me. :smiley:
