### ISSUE TITLE
Downtown Special - Kunio-kun no Jidaigeki Da yo Zenin Shuugou! (J)save issue

### ISSUE THREAD

**Issue by yuya495** [rdanbrook/nestopia#156]
This game is sure to be saved is not why can usually save
It becomes from New game
![001](https://cloud.githubusercontent.com/assets/8580180/10645019/7e9c0e3e-7866-11e5-9685-970502dd29fd.jpg)

![amarecco0007](https://cloud.githubusercontent.com/assets/8580180/10644934/13222044-7866-11e5-8edf-eb2c3210d1da.PNG)
![amarecco0005](https://cloud.githubusercontent.com/assets/8580180/10644940/17144da8-7866-11e5-9a7e-420611500d2d.PNG)
![amarecco0012](https://cloud.githubusercontent.com/assets/8580180/10644944/19e9876e-7866-11e5-813f-89f47a5c101e.PNG)

**Comment by yuya495** [comment]
The test was emulator EmuCR-Nestopia-UE20151021 latest version
It becomes and Nestopia1.40

**Comment by rdanbrook** [comment]
Lo siento, no comprendo tu Inglés.

Can you please clarify how to reproduce the problem and what the problem actually is? Is the SRAM not working or something?

**Comment by yuya495** [comment]
I tried to reproduce the bug in nestopia and the actual equipment in the video
https://www.youtube.com/watch?v=2jgNx42QPO4&feature=youtu.be

**Comment by dragon2snow** [comment]
<game>
        <cartridge system="Famicom" dump="unknown" crc="DC45A886" sha1="E42B77A11280EB0C99D654CD08B8933FA8DDB999">
            <board mapper="4">
                <prg size="128k" />
                <chr size="128k" />
                <wram size="8k"  battery="1" />
            </board>
        </cartridge>
    </game>

add battery="1" in database

**Comment by dragon2snow** [comment]
nestopia db xml this game not add battery

**Comment by yuya495** [comment]
Hello rdanbrook and dragon2snow this problem
You think you can fix?

**Comment by dragon2snow** [comment]
rdanbrook add nestopia db .
to fixed:
<game>
    <cartridge system="Famicom" dump="unknown" crc="DC45A886" sha1="E42B77A11280EB0C99D654CD08B8933FA8DDB999">
        <board mapper="4">
            <prg size="128k" />
            <chr size="128k" />
            <wram size="8k"  battery="1" />
        </board>
    </cartridge>
</game>

**Comment by yuya495** [comment]
外部データベースでNesCarts (2012-10-22).xmlをnestopia UEで
読み込んで使用するとDowntown Special - Kunio-kun no Jidaigeki Da yo Zenin Shuugou! (J)は保存できるようになるのですがGradius II (J)などのグラフィックが変になったりしますnestopia
 UE内部データベースだとGradius II (J)のグラフィックは良いのですがDowntown Special - Kunio-kun no Jidaigeki Da yo Zenin Shuugou! (J)が保存できませんでした
![amarecco0013](https://cloud.githubusercontent.com/assets/8580180/10665805/b3016122-7908-11e5-8a35-b89ae5d894ce.PNG)
![amarecco0014](https://cloud.githubusercontent.com/assets/8580180/10665810/b7e84dc2-7908-11e5-9064-1b0ace790267.PNG)

**Comment by yuya495** [comment]
NesCarts the (2012-10-22) .xml in nestopia UE in an external database
Loading will be used when the Downtown Special -! Kunio-kun no Jidaigeki Da yo Zenin Shuugou (J) is I will be able to save, but you can become a strange graphics, such as Gradius II (J) and nestopia
  It's UE internal database of Gradius II (J) graphics is good but Downtown Special -! Kunio-kun no Jidaigeki Da yo Zenin Shuugou (J) could not be saved
![amarecco0013](https://cloud.githubusercontent.com/assets/8580180/10665839/e45fb890-7908-11e5-9028-91dc7297dbd9.PNG)
![amarecco0014](https://cloud.githubusercontent.com/assets/8580180/10665840/e6b6b328-7908-11e5-8905-ed4606dfd8b9.PNG)

**Comment by rdanbrook** [comment]
I will investigate the root causes of this problem soon.

**Comment by yuya495** [comment]
Thank you if you could thank you for research and bug fixes rdanbrook

**Comment by rdanbrook** [comment]
I added dragon2snow's suggestion for the DB entry, please let me know if that fixes the problem.

**Comment by yuya495** [comment]
Nde read the updated NstDatabase.xml in external database where it tried to test play Downtown Special -! Kunio-kun no Jidaigeki Da yo Zenin Shuugou to could also save the (J)
Gradius II graphics also of the database that was not a problem of (J)
Thank you update it was cheers for good work
Is this issue is better to closed is?

**Comment by yuya495** [comment]
Nde read the updated NstDatabase.xml branches master in the external database where it tried to test play Downtown Special -! Kunio-kun no Jidaigeki Da yo Zenin Shuugou to could also save the (J)
Gradius II graphics also of the database that was not a problem of (J)
Thank you update it was cheers for good work

**Comment by yuya495** [comment]
rdanbrook and dragon2snow is really thanks
