### ISSUE TITLE
GPLv3 compatibility

### ISSUE THREAD

**Issue by Kekun** [rdanbrook/nestopia#157]
Nestopia is licensed under GPLv2, which is great, but forbid it to be linked (as a Libretro core) to any non GPLv2 licensed code.

Could you consider using a more permissive license? GPLv2+ which is exactly the same GPLv2 but provides compatibility with more recent versions of the GPL. Or even some sort of LGPL could be considered.

Doing so would allow RetroArch and GNOME Games to use Nestopia as a Libretro core as they are licensed under the GPLv3 license.

**Comment by rdanbrook** [comment]
It has always been GPLv2+. I am not going to re-license as GPLv3 because it is too political, and I will reject any pull requests that have changed the license.

I'm not sure if I need to change COPYING, but in all of the source code itself there is a GPLv2+ header.

Is there interest in including it in GNOME games? That would be cool.

**Comment by Kekun** [comment]
Oh, sorry for disturbing you, I should directly check the headers and not the COPYING files... I don't know if the copying is good or not then.

If by "it" you mean Nestopia, it already is in GNOME Games, it's in the "retro-plugins-nes" package: I should probably change how these plugins are handled to keep the emulator branding.

**Comment by rdanbrook** [comment]
From COPYING:
```Each version is given a distinguishing version number.  If the Program
specifies a version number of this License which applies to it and "any
later version", you have the option of following the terms and conditions
either of that version or of any later version published by the Free
Software Foundation.  If the Program does not specify a version number of
this License, you may choose any version ever published by the Free Software
Foundation.```

So COPYING does not need to be updated.
