### ISSUE TITLE
Issue of disk change of FDS

### ISSUE THREAD

**Issue by yuya495** [rdanbrook/nestopia#158]
Of FDS
disk1 side A
disk1 side B
disk2 side A
disk2 side B
To eject
When you are so assigned a shortcut key function
And I appreciate Become a very convenient
What useless?
![amarecco0021](https://cloud.githubusercontent.com/assets/8580180/10753623/b3e8bb96-7cd5-11e5-9782-0c2fcc06dcd3.PNG)

**Comment by rdanbrook** [comment]
Sorry, I'm not sure what you're trying to say. You could use a free translation tool if English is not your first language.

**Comment by yuya495** [comment]
私の英語が下手ですいません
ディスクシステムのショートカットキーに
ディスク1  A面
ディスク1  B面
ディスク2  A面
ディスク2  B面
取り出し
にショートカットキーを割り当てれるようにしてもらうことは
できませんでしょうか？
その機能があるととても便利に思います

**Comment by yuya495** [comment]
私の英語が下手で申し訳ないです
ディスクシステムのショートカットキーに
ディスク1  A
ディスク1  B
ディスク2  A
ディスク2  B
取出し
をキーマッピングに割り当てるようにしてもらうことは
できませんでしょうか？
その機能があるととても便利に思います
![amarecco0022](https://cloud.githubusercontent.com/assets/8580180/10761873/b6d32ca2-7d06-11e5-8708-ee592fcfd7ad.PNG)

**Comment by rdanbrook** [comment]
I see, so you want the ability to assign a hotkey to the "Eject FDS Disk" function?

**Comment by yuya495** [comment]
rdanbrookさん　そのとおりです　ゲーム内でディスク２　Bをセットして下さいと指示された時にshift+Bを
してもディスク１のAとBを替えるだけなのでメニュバーを開いてディスク2 Bをクリックしないとゲームの進行が
できないのでをキーマッピングに割り当てるようできると助かります

**Comment by yuya495** [comment]
そのとおりですrdanbrookさんゲーム内でディスク2 Bに替えてくださいと指示されたときにshift+Bで
ディスクチェンジしてもディスク1のAとBをずっと切り替えるだけなのでメニュバーで開いてディスク2 Bをクリックしなければゲームの進行ができないのでキーマッピングに割り当てるようにできるととても便利で助かります画像はに日本人作者のNESエミュレーターのキーマッピングです
![amarecco0023](https://cloud.githubusercontent.com/assets/8580180/10763257/95cfa80e-7d0c-11e5-8c47-61ed87a1b189.PNG)
![amarecco0027](https://cloud.githubusercontent.com/assets/8580180/10763287/b98cc312-7d0c-11e5-9cfa-f9f5c5c9bbaa.PNG)

**Comment by yuya495** [comment]
はい
![amarecco0027](https://cloud.githubusercontent.com/assets/8580180/10868327/d1d95a46-80ce-11e5-8cc0-dd4f24019724.PNG)
nesutopiaのinput optionsでdisk1 sideAとdisk1 sideB とdisk2 sideAとdisk2 sideB.とEjectに
キーマッピングする機能がほしいのです画像はVirtuaNESのキーマッピングです

**Comment by yuya495** [comment]
はい
nesutopiaのinput optionsでdisk1 sideAとdisk1 sideB とdisk2 sideAとdisk2 sideB.とEjectに
キーマッピングする機能がほしいのです画像はVirtuaNESのキーマッピングです

**Comment by yuya495** [comment]
![amarecco0027](https://cloud.githubusercontent.com/assets/8580180/10868343/55f2d924-80cf-11e5-83d6-81f9267e7faa.PNG)

**Comment by yuya495** [comment]
More keyboard shortcuts for FDS.
Do not allow the addition of these features?

**Comment by rdanbrook** [comment]
Out of scope.
