### ISSUE TITLE
Broken FDS emulation: Kiki Kaikai - Dotou Hen 

### ISSUE THREAD

**Issue by dragon2snow** [rdanbrook/nestopia#160]
http://forums.nesdev.com/viewtopic.php?f=3&t=6504
Hi everyone. I began to write a guide on how to play this FDS port of the Taito arcade game Kiki Kaikai (the series that came to be known as Pocky & Rocky on the SNES), but I have come across a strange problem. There are two boss fights that crash just about every modern NES emulator that I have tried, including FCEUX, Nestopia, Nintendulator, Mednafen, and VirtuaNES. The _only_ emulator that the game works properly on is the "old" emulator NNNesterJ. It's very strange, where those five other emulators hang, NNNesterJ goes swimmingly right along. (Interesting to note, for those of you who can read Japanese, a warning to this effect is present on this page: http://www25.atwiki.jp/famicomall/pages/244.html which you can run through Google Translator if need be.) 

It's not too hard to get to the crash point, although it takes a few minutes of walking (if you avoid all of the enemies.) The ROM that I'm using (and the only one that seems to be available) is from the TOSEC set with a CRC of 4C791779. From the start point, walk straight up. Keep following the path north until you get the first chance to travel east (you'll cross a few bridges just before that point.) Head east as soon as you are able, and then take the very next path south. This will lead you down and around to the entrance of a cave. You need 50 Ofuda cards to enter the cave, which is what you start with (you earn Ofuda cards by defeating enemies with your wand). Once inside, the path to the boss never branches. You travel north, then east, and the north. At the top of the second north path is the boss room. The expected result (and the one which NNNesterJ produces) is that the room scrolls into view, turns blue, and a large boss starts to attack you. The actual result in the rest of the emulators I've tried is that they hang before the room turns blue, stuck playing one note. 

I know this is the sort of thing that is incredibly low priority in the grand scheme of things, but I thought it might be interesting for some of the more active emulator developers to look at and try to figure out what NNNesterJ is doing differently (correctly or perhaps incorrectly) that allows the game to play in this one particular emulator. I would love to know myself. Thanks for taking a look! 

Procyon

**Comment by joepogo** [comment]
Hey Dragon, can you please send me the code to get dracula II fds working in nestopia or post it here? Please let me know.

**Comment by dragon2snow** [comment]
sorry ,I use only, not updated

**Comment by joepogo** [comment]
LOL yes you do update nestopia still. This is bullshit honestly. Sorry rdanbrook but you know this is, its not right someone comes on here and asks for your help but refuses to help anyone else. Anyways im done here, i thought by now the baked beans would be good and slow cooked. Im waiting for the sad sob story about i lost my love and job now that he has been called out for source. Anyways good day dragon! :P

**Comment by joepogo** [comment]
So dragon2snow are you ready to share some source with us yet? Let's see here:

Oh yea, check this link:

http://nestopia.gamemw.com/index.php/26-nestopia-plus-1-4-0-9-r230

;)
