### ISSUE TITLE
Problems with Windows 8.1 (also a request)

### ISSUE THREAD

**Issue by JorgeHawkins** [rdanbrook/nestopia#161]
I've testing the newest build of this NESTopia reboot, and working excellently thus far...
until you switch between a ROM and another or between fullscreen and windowed mode.
I applied most compatibilty settings to the emulator to no avail.
It keeps freezing every once on a while.

Which API are you using for this? Is still DirectDraw/Direct3D? 
Because if you're using them, maybe that's the main problem, as
DDraw has been fully deprecated in W8.
You should check this. 

And I have a request, maybe you can help me.

- When you switch between the sides of a FDS rom, a message in
red appears in the bottom left of the screen. Even when disabling the
option in the Preferences menu, this message keeps appearing and
it's driving me nuts. I want to disable ALL MESSAGES ON SCREEN,
that makes emulation feel better.

**Comment by rdanbrook** [comment]
On Windows it uses Direct2D. I'm no expert on that subject.

I'll see about disabling the FDS messages, but the long-term goal here is to have a cross-platform build that is easier to maintain rather than keeping this really old legacy Windows-only code alive.

**Comment by JorgeHawkins** [comment]
You can use a DDraw wrapper on it and it works almost flawlessly, even in 8. 
(In 7 there's no need.)
If you could add the removal of FDS as an option on a future revision, it would automatically transform this into my absolute favorite emulator!
