### ISSUE TITLE
Talespin flickering issues

### ISSUE THREAD

**Issue by joepogo** [rdanbrook/nestopia#163]
Im currently trying to track down which "fix" borked this. But something along the way has messed up talespin causing it to flicker on the pause screen and also when you complete a level and go to spend your money you see flickering in the eyes of the guy and the girl as they are talking. Sorry, lol,  I cannot remember the names of both. 

I tested this against the real thing and this does not happen. I also tested a clean nestopia 1.40 and this does not happen as well. :)

Dragon2snow can you confirm this as well on your builds of nestopia?

**Comment by dragon2snow** [comment]
Nestopia UE 1.46 not flicker

Can you upload a video or picture?

**Comment by joepogo** [comment]
Nevermind, it was my mistake.
