### ISSUE TITLE
black screen when loading game

### ISSUE THREAD

**Issue by artynet** [rdanbrook/nestopia#164]
just built from source the latest stable version (v1.47) on ubuntu 14.04 LTS. When loading a game I completely get no video output, what is wrong with my system ? I had to turn back to v1.46.2 to make all properly working....My video card is an ati hd6970 with proprietary drivers installed, might the very drivers affect the emulator behaviour ?

Regards, Arturo

**Comment by rdanbrook** [comment]
It is most likely the shader programs failing to compile. Try running the program from the terminal, and see if there are any messages about shader programs.

You may have better luck with the open source AMD drivers, which are the only ones I have tested (since I only have access to super low-end AMD graphics hardware).

Long story short, you need solid OpenGL 3.2 support.

**Comment by artynet** [comment]
here's the output when launching a game :

```
Failed to read config file /home/arturo/.nestopia/nestopia.conf: Using defaults.
0 joystick(s) found:
Failed to load input config file /home/arturo/.nestopia/input.conf: Using defaults.
OpenGL: 3.2.13399 Core Profile Context 15.20.1013
Database: 2901 items imported from internal DB
Fds: BIOS ROM ok
Ines: warning, unknown or invalid header data!
Ines: 256k PRG-ROM set
Ines: 256k CHR-ROM set
Ines: 840k W-RAM set
Ines: vertical mirroring set
Ines: NTSC set
Ines: mapper 5 set
Board: EKROM
Board: 256k PRG-ROM
Board: 256k CHR-ROM
Board: 8k auto W-RAM
Region: NTSC
Failed to compile vertex shader
Failed to compile fragment shader
Failed to link shader program
Audio: libao - 44100Hz, 16-bit, 1 channel(s)
Port 1: Standard Pad
Port 2: Standard Pad
```
any thoughts on this ? Thanks, Arturo

**Comment by rdanbrook** [comment]
Try the open source driver and see what happens.

**Comment by rdanbrook** [comment]
Closing this issue as there has been no response.
