### ISSUE TITLE
Default sound output hertz too low

### ISSUE THREAD

**Issue by CharlesCorrin** [rdanbrook/nestopia#169]
In the Sound Options screen, if you click "Default", the sound output will be set to "22050". This is too low and makes the audio sound bad. In older Nestopia versions, the default was 44100, which sounds much better and more like the real NES. Was this change a mistake?

I'm using the latest Windows version, 1.47 win32.

**Comment by rdanbrook** [comment]
https://github.com/rdanbrook/nestopia-win32
All win32-related stuff should go here. I am not actively developing the old Windows port, it is in maintenance mode, but I am accepting pull requests.

**Comment by anikom15** [comment]
This is purely informational: for performance reasons, you should choose the native mode for your sound card. This is usually 48 000 Hz, but older (and ironically high end) sound cards may be 44 100 Hz. Typically there shouldn't be any performance issues (the sound card can handle just about anything it's given) and anything above 32 000 Hz is fine.
