### ISSUE TITLE
[win32] Bugs and minors (video on youtube from me)

### ISSUE THREAD

**Issue by kirpich3** [rdanbrook/nestopia#170]
Hello.
My English is very bad.
I created video.
Thanks for beautiful emulator :)
[https://youtu.be/xAPZYzy_Rds](https://youtu.be/xAPZYzy_Rds)
---
And screenshot with idea (chat):
[http://i65.tinypic.com/fdh8wo.jpg](http://i65.tinypic.com/fdh8wo.jpg)

**Comment by rdanbrook** [comment]
The place for these bug reports is https://github.com/rdanbrook/nestopia-win32

I am also not actively developing that codebase at this point, but I am accepting pull requests.
