### ISSUE TITLE
Missing rows in the intro of Zelda II

### ISSUE THREAD

**Issue by PPLToast** [rdanbrook/nestopia#171]
Hi, I wanted to take a screenshot of The Adventure of Link and then I noticed rows were missing from the middle of the screen. In the gif I have 1.46 and 1.47. I have no clue if this is some weird bug and specific to this game though, notice how the sword isn't affected by it.

https://i.imgur.com/9xb1zzS.gif

**Comment by rdanbrook** [comment]
You are correct... there is a problem. This is related to sprite 0 hit timing. I've encountered this issue in the emulator I am writing from scratch. Thanks for pointing it out!

**Comment by PPLToast** [comment]
Huh, that's pretty interesting. Good to know, and no problem :)

**Comment by SigmaVirus** [comment]
Don't know if this is relevant or not but the FDS version seems unaffected with no rows missing, so it's safe to say that only the NES version is affected.

**Comment by dragon2snow** [comment]
there is not a problem.
Zelda II The Adventures of Link 2 (NES) Gold edition working pic.
![s-l1600](https://cloud.githubusercontent.com/assets/4350811/14065086/8a46c112-f44d-11e5-9bef-7584d5d1afe7.jpg)

**Comment by SigmaVirus** [comment]
Now that's even more interesting actually.

**Comment by rdanbrook** [comment]
Yes, the current behaviour is the correct behaviour. I just confirmed using the North America release and the Japanese FDS release.

**Comment by PPLToast** [comment]
I was curious and decided to check a few videos. The lines are present in all of Nintendo's emulators on GBA, NGC, 3DS, Wii and Wii U! Not that I know, but I guess this relies on something really precise to remove those lines that the "official" emulators don't do. Certainly interesting whether this thing is intentional or not, and if it also happens on all versions of the game. Maybe even consoles could affect it. Might look more into this later...

**Comment by rdanbrook** [comment]
I did the tests on an AV Famicom.

I tested other emulators, Mednafen has incorrect behaviour, FCEUX has correct behaviour. Mednafen's NES emulator is based on an older FCEU, and I'll take a wild guess that Nintendo's "official" emulator is also FCEU. Could be wrong, though.

**Comment by rdanbrook** [comment]
0f87538c2964214e99e3216cc290c54c6a3c7d6b
That's the commit that fixed the issue. So the Burai Fighter fix seems to have fixed other issues, including some we probably haven't noticed.
