### ISSUE TITLE
Allow hide mouse pointer for use with newer light gun devices

### ISSUE THREAD

**Issue by jjfmz42015** [rdanbrook/nestopia#173]
Newer light guns work great on duck hunt. but with cursor showing it makes the game too easy.

would be nice to be able to hide the cursor for those using a mouse gun rather than a mouse.

I have an older version of nestopia that had this done to it and am stuck using it for my gun games. would be nice if a Nestopia UE with this option came out because then one emulator will do all I need.

Thanks

**Comment by rdanbrook** [comment]
This is actually a great idea. It should be very easy to add.

**Comment by jjfmz42015** [comment]
I thought you would agree. I think it's as simple as replacing the pointer image with a transparent one. Would be best to allow switching between current one and transparent one that way both ppl with a gun like me and ppl with a mouse can enjoy gun games.
Ide also like to say thank you for this emulator! I love it.
On Apr 13, 2016 11:08 PM, rdanbrook <notifications@github.com> wrote:This is actually a great idea. It should be very easy to add.

**Comment by rdanbrook** [comment]
I just made an option to disable the cursor in general. It's nice to have that turned on when playing a non-zapper game too.

**Comment by jjfmz42015** [comment]
I guess this will show when 1.48 is released?

**Comment by rdanbrook** [comment]
Yes, or you can just compile the latest revision.

**Comment by jjfmz42015** [comment]
So I downloaded WIndows binary 1.48 which lists Added an option to disable the cursor in the change log but cant tell where this option is.

Help :)
