### ISSUE TITLE
MAME ROM Format Loading

### ISSUE THREAD

**Issue by anikom15** [rdanbrook/nestopia#177]
http://www.progettoemma.net/mess/lsset.php
Scroll down and you'll find the NES and Famicom sections.

Since I'm using MAME a lot now it would be nice to be able to use MAME's software list formats in Nestopia. Unfortunately the filenames vary considerably, so the only way to handle this is some sort of database I guess. The archives are made of PRG and optional CHR ROMs. Famicom Disks have a .dsk extension.

**Comment by rdanbrook** [comment]
I'm not going to add that to Nestopia, because it's probably too ambitious and I have other goals for this project. On the other hand, I am interested in this generally, and I might support this in my new emulator.
