### ISSUE TITLE
space shadow (J) is not working correctly

### ISSUE THREAD

**Issue by joepogo** [rdanbrook/nestopia#179]
The lightgun game space shadow is not working correctly. It gets hung after you kill the first alien. Not sure if this is a mapper issue or regression. After reading through old posts martin seems to state that it works but every dump i have tried hangs and the screen flashes when you shoot, which it should not do.

**Comment by dragon2snow** [comment]
working fine.

**Comment by joepogo** [comment]
Ive tried numerous dumps and none of them work correctly..I  am not sure what I could be missing. When you shoot the gun the screen flashes everytime and once you kill the first alien it just sits there after it drops the ammo.

**Comment by rdanbrook** [comment]
Did you find a solution?

**Comment by joepogo** [comment]
Hey brother, yea. It was an error on my end. You have to hit up after killing an alien. It was a mistake on my part. Im trying to help get the SOROM issue and 5011 channel issues sorted. Sorry for the false alarm.

**Comment by dragon2snow** [comment]
SOROM is 32K WRAM is ok.
MMC5 5011,nestopia is correct,First write 5010, again write 5011

**Comment by joepogo** [comment]
Since when was SOROM working correctly? There is no accurate fix for it yet is there?
