### ISSUE TITLE
X-input not being recognize

### ISSUE THREAD

**Issue by jvhellraiser** [rdanbrook/nestopia#180]
I can't configure the emulator, emulator acts weird when trying to configure the input.
I have Xbox 360 controller and XboxOne controller + wireless adapter for win 10 but
is basically imposible to configure pads in the emulator if the controller uses X-Input.
right at this moment i believe this emulator wont work with any X-input device controller.

**Comment by rdanbrook** [comment]
What build are you using?

**Comment by jvhellraiser** [comment]
I believe is the latest version that got  release or build this morning,Nestopia Git (2016/05/20)
![capture](https://cloud.githubusercontent.com/assets/16488761/15445321/740e4468-1eca-11e6-80ae-9e29a5ac3df1.PNG)

**Comment by rdanbrook** [comment]
A quick google search suggests using XInputPlus. The build you're using is of the old win32 port that I have put on life support. I don't have any plans to update it to use a more modern DirectX, but I am accepting pull requests if someone else wants to.
