### ISSUE TITLE
Needs a way to load custom palettes.

### ISSUE THREAD

**Issue by wyatt8740** [rdanbrook/nestopia#182]
I wanted to try the BMF Final version 2 palette in Nestopia and ended up having to run a windows build in WINE to accomplish it. Nestopia UE needs to be able to load .PAL palettes in linux.

**Comment by rdanbrook** [comment]
Done last week.

**Comment by wyatt8740** [comment]
Sorry, had an out of date build. Re-cloned and it was there (though a UI to select a file would be convenient).
