### ISSUE TITLE
GCC 6 build error

### ISSUE THREAD

**Issue by alucryd** [rdanbrook/nestopia#183]
Hi, nestopia fails to build with GCC 6 unless "-fpermissive" is passed. Please find the build log here: https://paste.xinu.at/7lZRO/

**Comment by rdanbrook** [comment]
Thanks for letting me know. Will fix soon.

This is why Nestopia should have been written in C.

**Comment by alucryd** [comment]
No problem, thx for the prompt reply :)

**Comment by rdanbrook** [comment]
Should be fixed now. Let me know.

**Comment by alucryd** [comment]
Works like a charm, thx :)
