### ISSUE TITLE
No sprite limit don't working in netplay

### ISSUE THREAD

**Issue by MasterShredder** [rdanbrook/nestopia#184]
Set "No sprite limit" option, start netplay with "Teenage Mutant Ninja Turtles - Tournament Fighters (U)" ROM for example, select Shred (character) vs Hot (character), then start game. Sprites flicker despite the option.

**Comment by rdanbrook** [comment]
That's because taking the sprite limit off is a hack. The real NES will never allow such a thing, since only 8 sprites can fit in secondary OAM. So this is a non-issue technically.
