### ISSUE TITLE
Ports accidentally change in netplay if you change the host

### ISSUE THREAD

**Issue by MasterShredder** [rdanbrook/nestopia#185]
Set your port to "Machine" --> "Input" --> "Port 1" --> "Pad 1"
Create netplay game with you on 1-st host and partner on 2-nd host, then Drop/Leave, create new game with partner on 1-st and you on 2-nd. This can result in auto-setting your port to "Pad 2", and you have to manually change it to "Pad 1". This is obstacle during game tournaments.
If the port does not change for the first time, do the same again.

Please fix this!

**Comment by rdanbrook** [comment]
Working on the netplay portion of the win32 port is not within the scope of this project. I am accepting pull requests if anyone wants to work on it though.

If you want to use Nestopia for netplay, I recommend checking out RetroArch.
