### ISSUE TITLE
Sony CXA2025AS palette

### ISSUE THREAD

**Issue by eugene-s-nesdev** [rdanbrook/nestopia#186]
Can you add SONY_CXA2025AS_US.pal palette 
to nestopia and libretro package as you did with FirebrandX's palettes?
It's nice palette based on CXA2025AS IC, integrated with puNES emulator:
http://html.alldatasheet.com/html-pdf/46739/SONY/CXA2025/81/1/CXA2025.html

[SONY_CXA2025AS.zip](https://github.com/rdanbrook/nestopia/files/311001/SONY_CXA2025AS.zip)

Here is PAL-file extracted by FHorse:

**Comment by rdanbrook** [comment]
This is a really nice palette. I added it to the "extras" directory with the FirebrandX palettes.
If you want to use this with the libretro port, just copy it to the libretro system directory with the filename "custom.pal", and set the palette core option to "custom".
