### ISSUE TITLE
(libretro) "Auto mode" region autodetection

### ISSUE THREAD

**Issue by eugene-s-nesdev** [rdanbrook/nestopia#187]
Seems "Auto" mode in favored system doesn't work correctly,
both NTSC (USA, Japan) and PAL (Europe) Roms works in ntsc mode.

Here is attach - battletoads and double dragon NTSC and PAL versions.
If you've set region to "Auto", both of them MUST BE work without glitches
and **visually looks same** speed and sound tempo, despite PAL is 50Hz.
But seems PAL autodetection doesn't work:

[btdd_ntsc_pal.zip](https://github.com/rdanbrook/nestopia/files/313701/btdd_ntsc_pal.zip)

*NOTE*
Only NTSC and PAL need to be autodetected via Auto mode, but not Dendy and Famicom. 
If mode in ROM header can't be recognized then autodetect
will must set NTSC as default value.

P.S. Maybe multiplatform build have this problem too, but i cannot test it.

**Comment by rdanbrook** [comment]
I will take another look at this to get to the bottom of it as soon as I have the liberty.

**Comment by rdanbrook** [comment]
I can't seem to reproduce it. It always overrides the database entry when not set to auto, and it if there is no database present it will default to NTSC for "auto". Are you sure the database is being loaded?

**Comment by eugene-s-nesdev** [comment]
No, i don't loaded database. I can do it manually?

**Comment by rdanbrook** [comment]
Just put it into the libretro "system" directory and it should load automatically.

**Comment by eugene-s-nesdev** [comment]
Yes, you're right. Autodetection works correctly after adding NstDatabase.xml
