### ISSUE TITLE
(libretro) Turbo A/B as separate buttons

### ISSUE THREAD

**Issue by eugene-s-nesdev** [rdanbrook/nestopia#188]
Hey.
I have an request.
Can you add ability to set "Turbo A" and "Turbo B" as separate buttons in libretro-port?

Will be nice to able set "X" as "turbo A" and "Y" as "turbo B" on RetroPad:
![rarch1](https://cloud.githubusercontent.com/assets/13199529/16079392/5e4ba9c8-3314-11e6-8c58-44dcb60fae50.jpg)

like on some pirate controllers:
![8577354df9ad64e5b36329dc8fa4e489c27174e7](https://cloud.githubusercontent.com/assets/13199529/16079485/d3f92d9e-3314-11e6-95b8-efcb70684737.jpg)

**Comment by rdanbrook** [comment]
You're right, it would be nice, but that's actually up to the frontend and has nothing to do with the core. In fact, the Nestopia core has no concept of turbo buttons, and the oscillation is done in the frontend code for both the win32 and cross-platform ports.

You may want to petition the author of whatever frontend(s) you use. It looks like it's RetroArch in your case, but there are others as well these days.
