### ISSUE TITLE
Controller not mapping...

### ISSUE THREAD

**Issue by jvhellraiser** [rdanbrook/nestopia#189]
![capture](https://cloud.githubusercontent.com/assets/16488761/16545494/cd893dca-40fa-11e6-801e-ed279b79344a.PNG)

**Comment by rdanbrook** [comment]
It appears that it is setting everything to an axis value, are you sure the pad was plugged in while no sticks were being pressed in any direction?

I have no Xbone controller so I can't reproduce this.

**Comment by jvhellraiser** [comment]
i am pretty sure, no other controllers were plug in. 
sadly i will have to stop using this emulator to bad
cause is one of the best emulators out there.

**Comment by rdanbrook** [comment]
Were you pressing a button or was a stick activated during the time it was plugged in though? Maybe you should try unchecking "Z Axis" as well.
