### ISSUE TITLE
Update FirebrandX Unsaturated Palette to V6

### ISSUE THREAD

**Issue by Awakened0** [rdanbrook/nestopia#190]
This palette was recently updated to V6 with a more accurate cyan color. This is supposedly the final update according to the site: http://www.firebrandx.com/nespalette.html

**Comment by rdanbrook** [comment]
FirebrandX actually let me know about this a few days ago, but I did not have time to add it until now.

Thank you for the reminder, it is now added.

**Comment by Awakened0** [comment]
It still needs to be added as selectable in the core options of the Libretro version.

Thanks!
