### ISSUE TITLE
(multiplatform) xubuntu and reg.selector, problem again

### ISSUE THREAD

**Issue by eugene-s-nesdev** [rdanbrook/nestopia#194]
Hi, Rdanbrook. Sorry for disturbing you again.

I've just received recent laptop that capable modern OpenGL, so i can test region selector now.
I've freshly installed xubuntu 16.04.1 x86, downloaded lastest
nestopia-master, installed all libraries mentioned in readme:
(libglew-dev libsdl2-dev libgtk-3-dev libarchive-dev libao-dev)

Multiplatform-port compiled like a charm. But "favored system" selector doesn't work,
and i cannot understand why.
All needed settings saved in "/home/usrname/.nestopia/nestopia.conf" correctly:
> [misc]
> ; 0=Auto, 1=NTSC, 2=PAL, 3=Famicom, 4=Dendy
> default_system=2
for example.

But all of them really didn't work - test roms and games run at NTSC-mode.
Looks like "default_system=1" always set.

All needed settings saved also in GUI, and after restarting too, so i've totally confused what source of this problem.

I did test on another laptop, which doesnt support modern OGL.
Compiled on xubuntu 14.04 x86, installed all mentioned libraries + libepoxy-dev.
And received same problem again: despite i don't see anything, i hear NTSC-roms works on NTSC timings even if force PAL or Dendy saved in config.

When i compile libretro-core, it doesn't have this problems, and you can change region.  
* small note: you can change NTSC<->PAL, NTSC<->Dendy on the fly. 
But between PAL<->Dendy you need to reload ROM via retroarch gui. 
Only this small bug, but in general, selector works.

Can you help me to find the source of this problem?

-
binaries: http://hwm.us.to/famimusic/Upload/nst_1.48wip_x86.zip
test rom 1: http://forums.nesdev.com/download/file.php?id=2826 (http://savepic.ru/7604789.png)
test rom 2: http://forums.nesdev.com/download/file.php?id=6415 (it show NTSC/PAL/Dendy region on bottom right, also you can look at "cpu clock speed" test, it almost like overclock demo rom 1)

**Comment by emu-russia** [comment]
Other users reported me they don't have issues on debian jessie and opensuse 13.2
I've tried binary compiled another guy for me on debian jessie, but it doesnt help:

https://youtu.be/y4VU2anaXJY

**Comment by eugene-s-nesdev** [comment]
Other users write me they don't have issues on Debian Jessie and OpenSuse12.3
One guy compiled binary on Jessie for me, but it doesn't help:
 
https://youtu.be/jmbNzMn5E1I
(recorded on xubuntu live-flash)

**Comment by rdanbrook** [comment]
I can't reproduce this problem. Actually I am glad you posted 240pee, that is an awesome test rom. It confirms that the selector is working on my end, at least if you close and reopen the emulator. I guess I should make it work on the fly like the rest of the settings.
