### ISSUE TITLE
Left, Right, Top, Bottom Cropping for Core Like Standalone Emu [Libretro]

### ISSUE THREAD

**Issue by shinra358** [rdanbrook/nestopia#195]
a lot of games you can see cut offs in the sprites because it needs to be cropped and stretched to hide it. I would like this option to do so like the standalone emulator.

**Comment by shinra358** [comment]
Let me clariify. There is a crop overscan vertical and it fixes things that seem cut off at the top of the screen. But it also snips off part of the bottom of the screen which is unwanted because most of the time, there are no problems with the bottoms of the screen and graphics usually get cut off when mask overscan vertical is on.

**Comment by rdanbrook** [comment]
I want to write an article about overscan masking, because this topic just keeps coming up. In reality there should never be a horizontal overscan masking option, and the vertical option should crop both top and bottom. I have yet to see a CRT TV or PVM that does it differently. Try Dragon Quest/Dragon Warrior or Crystalis and you'll see a perfect example of why the bottom should be cropped.

**Comment by shinra358** [comment]
Again, even the normal emu has this. I don't care about what other things do. This isnt a tv. A tv as you said would already do this anyway. So it's pointly to describe what a tv does.  I don't want to see any black bars or scrambled graphics in my games, it's just that simple. You don't like stretched stuff? They that's you. You've been playing stretched games throughout the entirety of your life before the ps3 era even existed and didn't complain once. Doesn't make sense to crop a part of the screen that doesnt even need cropping.

Screw it, I'll just continue to use reshade to do it and just continue to scale back the retroarch ui in the options so that I can see the ui correctly. I shoud have know better to use logic.

**Comment by rdanbrook** [comment]
http://wiki.nesdev.com/w/index.php/Overscan

**Comment by rdanbrook** [comment]
"I've waited over 5 years for you to fix that." - shinra358

I owe you nothing. This is a project I do as a hobby. If you are rude to people, don't expect them to do anything for you. I don't like your attitude at all, and if this is really bothering you to this degree, it might be time to step away from your screen and remember there is a whole world out there.
