### ISSUE TITLE
Add Nes Ram Init option

### ISSUE THREAD

**Issue by joepogo** [rdanbrook/nestopia#197]
In light of the recent commit from koitsu to fix the f-1 proto it seems that certain nes startup ram combinations affect games in different ways.

 Discussion here: http://forums.nesdev.com/viewtopic.php?f=3&t=10845&start=60

. Would it be possible to add an option into the menu like the way rainwarrior implemented:

https://sourceforge.net/p/fceultra/code/3275/

I think the hotspot is near where koitsu changed the code. Have an option to set it to 0xFF, 0x00 and then one for random values?

More discussion here: https://github.com/rdanbrook/nestopia/commit/23bbf10a68058785702458dcb4181448959f00d6

**Comment by rdanbrook** [comment]
Done!
