### ISSUE TITLE
Holy Diver (J) [mapper 78] issue

### ISSUE THREAD

**Issue by eugene-s-nesdev** [rdanbrook/nestopia#206]
Hi, rdanbrook.
Holy Diver (J), [mapper 78, CRC = BA51AC6F]
works good on original Nestopia 1.40 and broken on lastest build.
Problems in-game, issues when scrolling level.

**Comment by rdanbrook** [comment]
Holy Diver will only work with NstDatabase.xml loaded, or a submapper of 3 being set in the header.

More details here:
https://wiki.nesdev.com/w/index.php/NES_2.0_submappers#078:_Cosmo_Carrier_.2F_Holy_Diver
http://bootgod.dyndns.org:7777/profile.php?id=4038
http://bootgod.dyndns.org:7777/profile.php?id=3968

Only one or the other will work without doing checksum matching, the default is for Cosmo Carrier to work.

I tested my latest build with a clean Holy Diver dump and it works when NstDatabase.xml is loaded.

**Comment by eugene-s-nesdev** [comment]
Thank you for answer, yes, i confirm it too.
