### ISSUE TITLE
Sound runs too fast on 120hz dispay

### ISSUE THREAD

**Issue by etking** [rdanbrook/nestopia#207]
On Dell XPS17 with 120hz display, the emulator sound runs too fast in all games and it does not seem to be possible to slow down the sound. Fixing through options or Nvidia driver settings (monitor refresh rate = application controlled) does not help, vsync is disabled in the emulator settings. Please fix, for example by controlling the monitor refresh rate or by allowing to set it in video options.

**Comment by rdanbrook** [comment]
What OS are you using? What build of the emulator are you using?

**Comment by etking** [comment]
OS is Windows 7 x64. Build used is http://www.emucr.com/2016/09/nestopia-git-20160929.html .

**Comment by rdanbrook** [comment]
I am no longer actively developing the legacy Windows port, it is in maintenance mode. I will continue to compile releases, but it is too much of a hassle to bring it up to speed with modern technology. The cross-platform port is the future of the standalone Nestopia, though it is not quite up to par on Windows. You may want to try RetroArch and the libretro port for the best experience on the Windows platform.
