### ISSUE TITLE
same turbo-pulse value gives different speed on multiplatform and libretro port

### ISSUE THREAD

**Issue by eugene-s-nesdev** [rdanbrook/nestopia#209]
I've attached quietust's turbocheck test results (testrom is included).
As you can see, i've tested turbo pulse "2" and "3" values, and it give
different results on multiplatform and libretro nestopia ports.

[turbo_chk.zip](https://github.com/rdanbrook/nestopia/files/622893/turbo_chk.zip)

p.s: 
This issue isn't really major, so maybe don't care about it.
Thank you for adding turbo-buttons to libretro-port.

**Comment by rdanbrook** [comment]
This issue is really difficult to resolve, because we're dealing with totally different frontends that use different libraries. It's interesting to see there is a test rom for this though.
