### ISSUE TITLE
mapping a button to the microphone key binding

### ISSUE THREAD

**Issue by twipley** [rdanbrook/nestopia#210]
Hello. I have great respect for the work here, although I have found one core feature to be missing.

It is the microphone support (for Nestopia UE through Retroarch, at least).

The request is not the support for external microphone as such, but rather button mapping to a simulated microphone.

Upon tapping the button, microphone usage is mimicked and after a few presses, the sought in-game effect arrives.

(I am coming from https://libretro.com/forums/showthread.php?t=3050 Thread: [Famicom] Nestopia UE Microphone button binding).

Hoping to hear back from you,
and that our interests converge!

Sincerely yours,
twipley

**Comment by rdanbrook** [comment]
Sorry for the late response. This does not seem to be currently in the core, unless you can point out the API calls... I can't seem to find them anywhere though. I'll leave this open in case I ever get the desire to implement it in the core.

**Comment by twipley** [comment]
thanks for the reply.

I remember that standalone Nestopia features such a microphone button.

Does this answer the question? Or, am I missing something? If it works in standalone Nestopia, does it mean it is written in the Nestopia core?

**Comment by rdanbrook** [comment]
I will revisit the win32 code and see exactly what it is doing there...

**Comment by wyatt8740** [comment]
@rdanbrook did you find anything? I'm now playing through FDS Zelda as well :|

**Comment by rdanbrook** [comment]
I could never figure out how it's being done in win32, or if it even works at all.

**Comment by wyatt8740** [comment]
It works in win32. I had to spam _player 2_'s microphone button, but that killed off the pol's voice enemies.
Need a save file?

**Comment by rdanbrook** [comment]
Actually what would be more helpful is helping me track down the piece of code that injects this into the emulator, so I know what input device is being used and how. I took a look before but could not find anything that led me to the answer.

**Comment by rzumer** [comment]
I assume you have seen this already, but in case this is what you were looking for, the input is defined in `NstApiInput.hpp`. In `NstInpPad.cpp` it is treated like another button. When polled, if the button is pressed, it is as if the microphone detects noise at the maximal intensity. The feature was introduced in version 1.24.

**Comment by rdanbrook** [comment]
@rzumer thanks for pointing that out, I did not see that previously...

I will try to add something to libretro and standalone soon.

**Comment by rdanbrook** [comment]
Ok, I have figured out how it works, and replicated the behaviour in the win32 port in standalone. Currently I have hardcoded it to the spacebar, until I figure out how I want to add this binding to the config. I also need to think about the best way to add it to libretro. Ideally it would be nice to actually process input from a real microphone, but that is not something that even exists in the win32 port, and I need more microphone games to test with. Currently I have only tested with Zelda no Densetsu. Basically, you have to keep tapping the space bar quickly to kill Pols Voice. I don't particularly like this, because I'd rather just press it once, but I need to study how the game actually processes mic input to understand.

**Comment by rzumer** [comment]
From what I can tell, the standard Famicom microphone detects binary input, so a threshold could be used to binarize real microphone input without changing the existing functionality. Ideally, this threshold should be user-adjustable and/or incorporate background noise reduction.

**Comment by rdanbrook** [comment]
OK, I added it to the libretro port using the L3 button by default. That means clicking your joystick, if you have one... of course it is remappable though.

**Comment by rzumer** [comment]
Should a new issue be created for potential microphone input support?

**Comment by rdanbrook** [comment]
Not at this point, because it's going to require more work and I'm about to leave my country for sabbatical, and will not be able to work on things until I'm settled down. I may do it if I get a few weeks with regular internet access and have nothing else going on.

**Comment by rdanbrook** [comment]
I don't have a microphone, so I can't even begin to work on this. I am open to it, but it needs to be done without imposing more dependencies on the codebase just for one very obscure feature that works in only a few games.

**Comment by rzumer** [comment]
SDL seems to be able to process audio input. Would you prefer creating a new issue in this repository or in the libretro fork?

**Comment by rdanbrook** [comment]
Ideally all issues should be in here, the main repository.
