### ISSUE TITLE
(libretro) sony palette

### ISSUE THREAD

**Issue by eugene-s-nesdev** [rdanbrook/nestopia#214]
https://github.com/rdanbrook/nestopia/issues/186
```
 I added it to the "extras" directory with the FirebrandX palettes.
If you want to use this with the libretro port, just copy it to the libretro system directory with the filename "custom.pal", and set the palette core option to "custom".
```
It's a problem. Most of of non-rooted android devices don't allow user write to libretro system directory.
Maybe will be better to put CXA2025AS with main palette package, like consumer, rgb, etc.
By the way: FirebrandX's "unsaturated-V7" and "Nostalgia" palettes almost the same thing.
"Nostalgia (FBX)" is final version of "Unsaturated -V5, -V6, -V7" series.

http://www.firebrandx.com/nespalette.html

**Comment by rdanbrook** [comment]
You're making good points here. I prefer the CXA2025AS palette and it's what I use now, and I thank you for bringing it to my attention in the first place.

The next time I have a free moment I will sort this out.

**Comment by eugene-s-nesdev** [comment]
In short words: "Nostalgia (FBX)" = "Unsaturated V8", so V7 isn't need.

**Comment by rdanbrook** [comment]
It's done.
