### ISSUE TITLE
Installation and destination folder Linux Mint 18.1

### ISSUE THREAD

**Issue by Vitali80** [rdanbrook/nestopia#216]
Tested on Linux Mint 18.1

- Impossible to select a destination folder with the command "prefix", this is so annoying
- Impossible to uninstall it with "sudo make uninstall"
- The software does not appear on the Start Menu, forcing to be added manually

**Comment by rdanbrook** [comment]
To change the destination directory you will need to adjust the CMAKE_INSTALL_PREFIX.

You are correct that sudo make uninstall does not function at this time.

If these are big problems for you at the moment, feel free to check out an older revision that still had the static Makefile. In the mean time I will add this to my to do list.

**Comment by Vitali80** [comment]
Thanks for your reply.

Thanks for continuing on Nestopia developing, this is a great emulator. In my opinion, its accuracy is higher and I played a lot of games fluently in comparison with other emulators for Linux.

**Comment by SoapGentoo** [comment]
@Vitali80 I've added an Autotools system. To use it, you need to bootstrap the autotools, after which you get the standard `./configure` script which fully supports `make uninstall`
