### ISSUE TITLE
Script/cmdline option for setting scale

### ISSUE THREAD

**Issue by bboydj** [rdanbrook/nestopia#220]
Great work you do on keeping this emulator alive and kicking!

In the UI there is this setting View -> Screen Size -> 1x.
Is there a way to set this via params called from externally, like cmdline or script etc.?

This would really be awesome, thanks in advance!
bboydj

**Comment by rdanbrook** [comment]
It sounds like you're using the win32 port. I stopped actively developing that port a long time ago, but I am accepting pull requests if you would like to add this feature. As far as I know it does not currently exist. If you're on Windows, you will get the best experience using the libretro port with RetroArch.
