### ISSUE TITLE
input.conf not saving/updating

### ISSUE THREAD

**Issue by kadamwolfe** [rdanbrook/nestopia#221]
I am trying to configure a controller to use with nestopia ue.  When I go Emulator -> Configuration -> Input, I am able to map buttons on my controller.  But once I click 'ok' and go back to input, it's flipped back to the default keyboard setting.  I -can- make edits to the mapped keyboard buttons.

When I exit, ~/.nestopia/input.conf saves the updated values for the controller, but it when I open nestopia it continually resets to keyboard input.

I've tried using a N64 controller via MayFlash USB adpater and a PSX controller, also with a USB adapter.
I'm using Linux Mint 18.1 (Ubuntu 16.04) and Nestopia UE v1.47 from the repos.

jstest-gtk recongizes both controllers equally well.

**Comment by rdanbrook** [comment]
You have to switch the dropdown menu to access the joystick configuration every time the config window is opened fresh. When you select the joystick item on the dropdown, you should see the values you entered previously.

**Comment by kadamwolfe** [comment]
omg... I feel pretty dumb now.  Thanks though.  That seems to be working.
