### ISSUE TITLE
[Request] Add per-game custom palette

### ISSUE THREAD

**Issue by jvook** [rdanbrook/nestopia#229]
Examine game.nes directory and system directory for game.pal and preferentially load instead of custom.pal when custom core option is selected.

https://github.com/rdanbrook/nestopia/issues/122

**Comment by jvook** [comment]
I use Castlevania 2 Moody hack (http://www.romhacking.net/hacks/880/) which includes a custom .pal file

**Comment by rdanbrook** [comment]
Done.
