### ISSUE TITLE
[patch] Fixed NSF and FDS in Dendy-mode

### ISSUE THREAD

**Issue by eugene-s-nesdev** [rdanbrook/nestopia#232]
Hi, Rdanbrook.
Here is correct patch for lastest master that fixes NSF and FDS in Dendy-mode (made by FHorse and feos)
[add-dendy-mode-to-fds-and-nsf-v4.zip](https://github.com/rdanbrook/nestopia/files/1079890/add-dendy-mode-to-fds-and-nsf-v4.zip)

**Comment by rdanbrook** [comment]
Thanks Eugene. Is there a reference available where I can see discussion on this issue? I will be on the road but will try to merge it when I get the chance.

**Comment by eugene-s-nesdev** [comment]
https://github.com/rdanbrook/nestopia/issues/215
FHorse (puNES developer) took feos patch (that fix NSF and FDS) and fixed it right way.
He sent me 2 patches - one for vanilla 1.40, and second for your lastest-master.
I tested patch on vanilla 1.40, and confirmed it work correct.
(your current master have temporary issue, so i cant test it
https://github.com/rdanbrook/nestopia/issues/226)

Patch contains minor NstNsf, NstFds and NstApu changes.
All the discussion with FHorse and feos was on ICQ.

I hope we'll fix regionselector sometimes.

**Comment by rdanbrook** [comment]
I have applied the patch. Thank you again for this work!
