### ISSUE TITLE
Multitap Support Broken for Famicom Games (Famicom 4 Player Adaptor)

### ISSUE THREAD

**Issue by mugenmidget** [rdanbrook/nestopia#235]
It seems that regardless of what's in NstDatabase.xml, Famicom 4 player games are not properly supported.  I can't get Bomber Man II (J) or Nekketsu Kakutou Densetsu (J) to work with more than 2 players.  If I use the same NstDatabase.xml in the original Nestopia v1.40, it properly detects that they are Famicom Multitap games and 3P/4P controls work fine.

**Comment by mugenmidget** [comment]
I think the issue might be caused by using "AutoSelectController" in libretro.cpp as the sole method for determining the desired controller:

`if (dbpresent)
   {
      Api::Input(emulator).AutoSelectController(0);
      Api::Input(emulator).AutoSelectController(1);
      Api::Input(emulator).AutoSelectController(2);
      Api::Input(emulator).AutoSelectController(3);
   }
   else
   {
      Api::Input(emulator).ConnectController(0, Api::Input::PAD1);
      Api::Input(emulator).ConnectController(1, Api::Input::PAD2);
      //Api::Input(emulator).ConnectController(1, Api::Input::ZAPPER);
      Api::Input(emulator).ConnectController(2, Api::Input::PAD3);
      Api::Input(emulator).ConnectController(3, Api::Input::PAD4);
   }`

Which calls this method:

`
		Result Input::AutoSelectController(uint port) throw()
		{
			if (port >= NUM_PORTS)
				return RESULT_ERR_INVALID_PARAM;

			Type type;

			if (emulator.image)
			{
				type = static_cast<Type>(emulator.image->GetDesiredController( port ));
			}
			else switch (port)
			{
				case PORT_1: type = PAD1;        break;
				case PORT_2: type = PAD2;        break;
				default:     type = UNCONNECTED; break;
			}

			return ConnectController( port, type );
		}`

So it looks like if the image is in NstDatabase.xml, it'll call "GetDesiredController".  But this method doesn't appear to do anything except for PAD1 and PAD2 to be connected:

`		uint Image::GetDesiredController(uint port) const
		{
			switch (port)
			{
				case Api::Input::PORT_1: return Api::Input::PAD1;
				case Api::Input::PORT_2: return Api::Input::PAD2;
				default: return Api::Input::UNCONNECTED;
			}
		}`

I'm not sure what the best way to fix that would be, but it looks like there's a method "AutoSelectAdapter" for determining if the Famicom adapter or US adapter is needed, so that might need to be called in some form.  Sorry if I'm way off base on any of this.

**Comment by mugenmidget** [comment]
Quick update, I changed the code I quoted above in libretro.cpp to have calls to AutoSelectAdapter and ConnectAdapter:

```
   if (dbpresent)
   {
      Api::Input(emulator).AutoSelectController(0);
      Api::Input(emulator).AutoSelectController(1);
      Api::Input(emulator).AutoSelectController(2);
      Api::Input(emulator).AutoSelectController(3);
      Api::Input(emulator).AutoSelectAdapter();
   }
   else
   {
      Api::Input(emulator).ConnectController(0, Api::Input::PAD1);
      Api::Input(emulator).ConnectController(1, Api::Input::PAD2);
      //Api::Input(emulator).ConnectController(1, Api::Input::ZAPPER);
      Api::Input(emulator).ConnectController(2, Api::Input::PAD3);
      Api::Input(emulator).ConnectController(3, Api::Input::PAD4);
      Api::Input(emulator).ConnectAdapter(Api::Input::ADAPTER_FAMICOM);
   }
```

This seems to make Famicom 4P games work and doesn't break US games.  Not sure if it's the right change to make, but I'm happy for now!

**Comment by hizzlekizzle** [comment]
Looks like just the one-line change to the dbpresent block fixes it for me (in the presence of the database, obviously). I'm not sure it's desirable to have it connected without the database.

**Comment by mugenmidget** [comment]
Yeah, good point. :)  I was trying to force it for hacks/translations not in the database, but it didn't seem to work regardless.

**Comment by rdanbrook** [comment]
This problem should be resolved by the latest PR.
