### ISSUE TITLE
Scaling values larger than 4

### ISSUE THREAD

**Issue by prg318** [rdanbrook/nestopia#240]
With 4K and Ultrawide displays becoming more commonplace, it would be great to see scaling values larger than x4 supported.

Could likely be posted as a separate issue/feature request, but it would also be great to see 'autoscaling' for fullscreen where the nes video output is scaled based on pixels available in the fullscreen window

**Comment by rdanbrook** [comment]
Done.

Autoscaling in fullscreen was already possible.
