### ISSUE TITLE
only YUV displays correct colors for Final Fantasy 1 and 2 random encounter transitions

### ISSUE THREAD

**Issue by xdavidliu** [rdanbrook/nestopia#244]
When the palette is in YUV mode (0 in the nestopia.conf file), the encounter transition animations in Final Fantasy 1 and 2 display correctly. For example, see this video at this moment: https://www.youtube.com/watch?v=xBUUekCp96c&t=18m51s

The correct transition from world map to battle screen is a very subtle flashing, where the screen flashes and dims slightly for about half a second. How do I know it's correct? well I couldn't find any videos of FF2 being played on console, but here's a similar moment with FF1 being played on a console https://www.youtube.com/watch?v=Km2qfa1JGbQ&t=9m26s (I'm assuming whatever video cables he used to output the video from console to Twitch faithfully reproduces the effect too), and the same style transition happens, which leads me to believe that this was the intended appearance of the effect: 

However, if I instead use RGB_mode (1) or any custom palette (2), the encounter transitions look completely different. Instead of a subtle dimming and flashing, the whole screen becomes psychedelic, flashing to extreme blues and yellows. Note that everything else in the game looks correct, it's just that the specific half a second transition animation to the battle screen is dramatically different, in an psychedelic and undesirable way.

The reason I am asking is because I would like to use a custom palette with the exact colors that YUV mode uses, except inverted, since I am using a system-wide invert colors setting, and would like to invert the nestopia palette in order to see the double-inverted, or correct, colors. However, since every .pal file I have found, even those named "YUV.pal", have the undesirable "psychedelic" colors during the battle transition when I use it with the custom palette (3) setting, I think it's something specific that is done when the YUV setting is applied (in particular, in video.cpp where there is the comment // Set YUV Decoder/Picture options), that is *not* done when RGB mode or a custom palette is applied. If this is true, what setting is it that gives the correct non-psychedelic appearance when YUV mode is used, and how can I also turn on that setting when I am using custom palettes?

**Comment by rdanbrook** [comment]
This is due a problem with the emphasis bits. Nestopia's emphasis bits are completely wrong, and there are even worse examples than in Final Fantasy.

https://wiki.nesdev.com/w/index.php/Colour-emphasis_games
This is a list of games that use the emphasis bits.

I will see if I can do anything quickly to fix that.

**Comment by xdavidliu** [comment]
ah okay, that link is very helpful and relevant. Just so I am understanding, am I correct in assuming that the non-psychedelic flashing was how it is supposed to look? And if so, does that imply that YUV mode (which is the only mode that gives that non-psychedelic flashing) is handling these emphasis bits correctly?

**Comment by rdanbrook** [comment]
The psychedelic flashing is incorrect. The YUV mode does handle the emphasis bits correctly.

**Comment by xdavidliu** [comment]
got it. Additionally, is there a quick and dirty way that you can think of for the time being that I can play in YUV mode, but with inverted colors? I tried simply replacing all the numbers in the pc10Palette and vsPalette arrays in source/core/NstVideoRenderer.cpp with FF minus the number, but all that did was get rid of the picture entirely.

**Comment by rdanbrook** [comment]
Probably the easiest way to invert the colours would be to do it at the frontend level rather than the core level. I actually don't fully understand how Nestopia's built in colour palettes work; using OpenGL to accomplish it might be easier. You could also use ^= on the colour bits instead and see what happens.

**Comment by xdavidliu** [comment]
got it, thanks
