### ISSUE TITLE
CMake link directories issue

### ISSUE THREAD

**Issue by bentley** [rdanbrook/nestopia#248]
Building with CMake fails with 1.48 on OpenBSD.

    FAILED: nestopia 
    : && /usr/ports/pobj/nestopia-1.48/bin/c++  -O2 -pipe -g -g   [filenames]  -o nestopia -L/usr/local/lib -lz -larchive -lao -lSDL2 -lepoxy -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib && :
    /usr/bin/ld: cannot find -lepoxy
    c++: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.

The trouble is that libepoxy is located in `/usr/X11R6/lib` on OpenBSD, but that directory is not passed via `-L`.

pkg-config does the right thing, so I’m not sure why CMake doesn’t pick it up:

    $ pkg-config --libs epoxy
    -L/usr/X11R6/lib -lepoxy

CMake configure output:

    -- The C compiler identification is Clang 4.0.0
    -- The CXX compiler identification is Clang 4.0.0
    -- Check for working C compiler: /usr/ports/pobj/nestopia-1.48/bin/cc
    -- Check for working C compiler: /usr/ports/pobj/nestopia-1.48/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/ports/pobj/nestopia-1.48/bin/c++
    -- Check for working CXX compiler: /usr/ports/pobj/nestopia-1.48/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Performing Test HAS_NO_NARROWING
    -- Performing Test HAS_NO_NARROWING - Success
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
    -- Found ZLIB: /usr/lib/libz.so.5.0 (found version "1.2.3") 
    -- Found LibArchive: /usr/local/lib/libarchive.so.10.1 (found version "3.3.2") 
    -- Checking for module 'ao'
    --   Found ao, version 1.2.0
    -- Checking for module 'sdl2'
    --   Found sdl2, version 2.0.5
    -- Checking for module 'epoxy'
    --   Found epoxy, version 1.3.1
    -- Checking for module 'gtk+-3.0'
    --   Found gtk+-3.0, version 3.22.21
    -- Performing Test HAS_NO_DEPRECATED_DECLARATIONS
    -- Performing Test HAS_NO_DEPRECATED_DECLARATIONS - Success
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /usr/ports/pobj/nestopia-1.48/build-amd64

**Comment by rdanbrook** [comment]
Do you have the same issue if you use autotools instead?

**Comment by bentley** [comment]
I don’t know how to work autoconf. This is what I get with that:

    cd /usr/ports/pobj/nestopia-1.48/nestopia-1.48 &&  AUTOCONF_VERSION="2.69"  AUTOMAKE_VERSION="1.15"  autoreconf -i
    configure.ac:35: installing './config.guess'
    configure.ac:35: installing './config.sub'
    configure.ac:105: installing './install-sh'
    configure.ac:105: installing './missing'
    Makefile.am: installing './depcomp'
    configure: WARNING: unrecognized options: --disable-gtk-doc
    configure: loading site script /usr/ports/pobj/nestopia-1.48/config.site
    checking whether configure should try to set CXXFLAGS/CPPFLAGS/LDFLAGS... no
    ./configure[1880]: AX_CHECK_ENABLE_DEBUG: not found
    checking build system type... x86_64-unknown-openbsd6.2
    checking host system type... x86_64-unknown-openbsd6.2
    ./configure[2002]: AX_COMPILER_VENDOR: not found
    ./configure[2003]: AX_COMPILER_VERSION: not found
    checking for a sed that does not truncate output... (cached) /usr/bin/sed
    checking whether the C++ compiler works... yes
    checking for C++ compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... (cached) o
    checking whether we are using the GNU C++ compiler... (cached) yes
    checking whether c++ accepts -g... (cached) yes
    ./configure[2585]: syntax error: `${cxxflags_test}' unexpected

**Comment by rdanbrook** [comment]
I am without a computer at the moment and will be for months probably... Can anyone else help with this?

**Comment by noabody** [comment]
On Ubuntu 17.04 without package "autoconf-archive" installed according to this post: [https://stackoverflow.com/questions/30412576/autotools-syntax-error-with-ax-check-compile-flag](url) generates an almost identical autoconf failure for me.

After installing that package and re-running "autoreconf -vif" everything seemed to work fine.

**Comment by SoapGentoo** [comment]
@bentley if the `pkg-config --libs` doesn't print `-L/usr/X11R6/lib`, then you should get this fixed in OpenBSD. For a crappy stop-gap solution, try doing `LDFLAGS="-L/usr/X11R6/lib" cmake blabla-whatever-you-pass-here` which should at least make it link.

**Comment by SoapGentoo** [comment]
@bentley sorry I misread, you're right. This is one of the reasons why I hate CMake, because it seems "easier"at first glance but in reality is a massive minefield of anti-patterns that fail in corner cases. I believe my PR should fix the issue.
