### ISSUE TITLE
ALL MC ACC games crashing on UE and other ports

### ISSUE THREAD

**Issue by joepogo** [rdanbrook/nestopia#253]
https://github.com/rdanbrook/nestopia/commit/1ed56ed256d32160a5329025c0e95e62f560dc80#diff-709a9d7a046611d12c0cb95b0cd6ab0e

This commit causes ALL games on MC-ACC to crash. I have been trying to track this bug down for quite some time on the xbox port and it crashes on undead edtion windows 32 and all other versions. I thought it was the xbox port but it's all versions. 

Not sure what part of the code is causing the issue, but something will not allow these games to run.

**Comment by dragon2snow** [comment]
remove NST_NO_VTABLE

**Comment by joepogo** [comment]
Thank you dragon2snow, which file? Is it the one here? Want to make sure i get this right, and why does this mess up the games?

`namespace Nes
{
	namespace Core
	{
		namespace Boards
		{
			namespace Acclaim
			{
				class NST_NO_VTABLE McAcc : public Board
				{
				public:
`

**Comment by dragon2snow** [comment]
yes

**Comment by joepogo** [comment]
I can confirm this works, however, why does removing that make it work? Can you please explain?

**Comment by dragon2snow** [comment]
NST_NO_VTABLE TAG :Classes that cannot be instantiated

**Comment by jjfmz42015** [comment]
hmmm just tested this and sure enough instant crash all MC-ACC games.

this problem is not present in FCEUX 2.2.3 also not present in Nestopia 1.40

**Comment by jjfmz42015** [comment]
so how would one go about compiling this with that removed?

**Comment by rdanbrook** [comment]
The best way would be for someone to give me a pull request. I have no computer right now, and am in a country with sparse internet service so I can't do it myself.

**Comment by jjfmz42015** [comment]
Oh if that's how then we should just wait for your return.

**Comment by joepogo** [comment]
I can verify it works. When I get home I will set up a pull request. All games on mc acc now no longer crash. I tested all of them.

**Comment by joepogo** [comment]
Pull request submitted.

**Comment by rdanbrook** [comment]
Thanks joepogo!!

**Comment by joepogo** [comment]
Heh, this was my first attempt so it was very confusing. Hopefully that went through ok. :P
