### ISSUE TITLE
FDS IRQ

### ISSUE THREAD

**Issue by dragon2snow** [rdanbrook/nestopia#255]
http://forums.nesdev.com/viewtopic.php?f=3&t=16507

**Comment by joepogo** [comment]
You already fixed the lutter freeze here:

https://github.com/dragon2snow/NestopiaPlus/commit/1b4fd56b893ce080e3ce3eefb264dba12f513593

And also you fixed the druid issue here:

https://github.com/dragon2snow/NestopiaPlus/commit/ecc8b532f7474deb21e19b0d792440a308cd2156

**Comment by joepogo** [comment]
Confirmed working. Does putter golf have sound?

**Comment by dragon2snow** [comment]
You already fixed the lutter freeze here:

dragon2snow/NestopiaPlus@ 1b4fd56 

And also you fixed the druid issue here:

dragon2snow/NestopiaPlus@ ecc8b53 
 this fixed not working Hikaru Genji - Roller Panic (1989)(Pony Canyon)[PNF-GEN].

**Comment by joepogo** [comment]
How do we get sound back on putter golf? It used to work. The lutter freeze did fix lutter from freezing. Can help?

**Comment by dragon2snow** [comment]
I am a game player! not emu dev.
now,I only dump fc game!
