### ISSUE TITLE
NES Overclocking

### ISSUE THREAD

**Issue by Papermanzero** [rdanbrook/nestopia#256]
SImilar feature like FCEUX

https://github.com/libretro/nestopia/issues/59
https://github.com/libretro/nestopia/pull/64

**Comment by rdanbrook** [comment]
This was implemented awhile ago.

**Comment by Papermanzero** [comment]
I did not find the option in the menu. I actually thought it is in the menu for sprite limiting.

**Comment by rdanbrook** [comment]
It's in ~/.nestopia/nestopia.conf
I'll add it to the GUI next time I do a commit.

**Comment by rdanbrook** [comment]
Actually it is already there, it's in the Misc tab.

**Comment by Papermanzero** [comment]
I am using the windows version. It is using nestopia.xml (~/.nestopia/nestopia.xml), which contains all settings. A misc section within the settings is not available. Therefore I though the overclocking is not implemented. 
I looked into Machine -> Options (in the windows gui) which would be an adequate place for the setting.

**Comment by rdanbrook** [comment]
In that case, this issue should be under the nestopia-win32 repo. I don't have a Windows development environment set up to do this, so maybe someone will do a pull request to add this feature. I recommend moving to the libretro port if you're on Windows, that is the future. Any features it is lacking will be added over time.
