### ISSUE TITLE
Unable to map high-numbered joysticks in Linux

### ISSUE THREAD

**Issue by Lou-Cipher** [rdanbrook/nestopia#262]
nestopia/source/unix/input.cpp utilizes hard-coded string indexes to identify axis vs. button vs. hat.  Because of this, it does not support joysticks numbered 10+, i.e. /dev/js10 (below 10 uses a single digit, i.e. /dev/js9).  Because I have usb adapters for a wide variety of vintage controllers, my joysticks are numbered js0 through js11, and it just so happened that my nes adapters are 10 and 11.  Because the code looks to string[2] for 0x61, 0x62, or 0x68 (for Axis, Button, Hat, respectively), it reports a malformed inputcode when attempting to manually configure the mappings in the config file, and actually crashes when pressing a button on a 2-digit joystick device to assign it to a controller.

I think I should have some free time this weekend, I'll poke around the code and see if I can write a patch.

**Comment by Lou-Cipher** [comment]
Just submitted a PR to fix this.  Be gentle, it's my first commit to a project not my own.

**Comment by rdanbrook** [comment]
Looks good, can't test until next week but it appears fine. Thanks for this!

**Comment by Lou-Cipher** [comment]
Can you revert that change?  I was ssh'd into the wrong box when I built and tested.  Seems to segfault whenever a joystick is present (even just one) at start.  Looking into it, working on a fix.

**Comment by Lou-Cipher** [comment]
Actually, ignore my last, I just reverted my commits locally and rebuilt, still segfaults, same place.  I'm going to open a new issue for this, I've got strace running now
