### ISSUE TITLE
Segfaults on Debian Sid/Buster with latest master

### ISSUE THREAD

**Issue by Lou-Cipher** [rdanbrook/nestopia#264]
I'm getting segfaults from builds of the latest master (including without my latest commits, figured I'd check that first :) ) when starting nestopia with any joysticks connected.  I've verified this is specific to sid/buster, and does NOT currently happen on a fully-patched Stretch install.  So, since Buster is a ways out, this might be low priority, could be a bug in a package in buster (I fear the systemd is involved...).  I've attached the stack trace, but here's the relevant bit:

`
select(8, [7], NULL, NULL, {tv_sec=0, tv_usec=0}) = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC_RAW, {tv_sec=250933, tv_nsec=212862857}) = 0
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
select(4, [3], NULL, NULL, {tv_sec=0, tv_usec=0}) = 0 (Timeout)
read(19, 0x7fffba981500, 768)           = -1 EAGAIN (Resource temporarily unavailable)
read(18, 0x7fffba981500, 768)           = -1 EAGAIN (Resource temporarily unavailable)
read(17, 0x7fffba981500, 768)           = -1 EAGAIN (Resource temporarily unavailable)
read(16, 0x7fffba981500, 768)           = -1 EAGAIN (Resource temporarily unavailable)
read(15, 0x7fffba981500, 768)           = -1 EAGAIN (Resource temporarily unavailable)
read(14, 0x7fffba981500, 768)           = -1 EAGAIN (Resource temporarily unavailable)
read(13, 0x7fffba981500, 768)           = -1 EAGAIN (Resource temporarily unavailable)
read(12, 0x7fffba981500, 768)           = -1 EAGAIN (Resource temporarily unavailable)
read(11, 0x7fffba981500, 768)           = -1 EAGAIN (Resource temporarily unavailable)
read(10, 0x7fffba981500, 768)           = -1 EAGAIN (Resource temporarily unavailable)
read(9, 0x7fffba981500, 768)            = -1 EAGAIN (Resource temporarily unavailable)
read(8, 0x7fffba981500, 768)            = -1 EAGAIN (Resource temporarily unavailable)
select(8, [7], NULL, NULL, {tv_sec=0, tv_usec=0}) = 0 (Timeout)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV +++
`
That repeats over and over until it decides to die there at the end.  Also worth noting, the packaged 1.48-1 in debian's repos does not have this issue.  Further, I decided to build 1.48-release from source, it also does not have this issue (interesting but unrelated note, both the deb package version and the 1.48 from source DO both segfault, but on exit, and with a completely different error in the trace).  So, we can conclude that some change or combination of changes out of the past 88 (well, 85 I guess, since it appears to predate at least my changes) is causing this segfault.  I'll dig into it further.

[nestopia.txt](https://github.com/rdanbrook/nestopia/files/1549911/nestopia.txt)

**Comment by Lou-Cipher** [comment]
OK, I've done some troubleshooting, whatever is segfaulting is in the call to gtk_main().  I've never messed with gtk, so I'll have to dig some to figure out what's what from here, might be a while. But it makes sense, lots of package updates to gtk, bound to be some kind of compatibility issues...

**Comment by PartyImp** [comment]
full backtrace: https://gist.github.com/PartyImp/caf39f839194cdff73ddfc7631f433ee

**Comment by Lou-Cipher** [comment]
Hah, and that right there is why you call up the big guns.  If I were a betting man, I'd guess our culprit is somewhere in one of these three commits:

ce724baf2cd87b0c870001ff99b3b2cb33da21ab
26c3404e8dabbb4992e57fe30afd3c9070622605
b472481b19d5cfa24fc24764c22c4c1f0e3da11e

But that can wait until tomorrow.  Thanks @PartyImp !

**Comment by rdanbrook** [comment]
Unfortunately I will not have access to my computer until mid to late next week, I am still travelling. So, this might take me that long to fix. It does appear to be input related from the back trace. It could be crashing on previous commits due to parsing your new input config file with values that would be invalid for that revision.

**Comment by Lou-Cipher** [comment]
No worries, I know what function is crashing now, so I'm going to take a look. And I did a test build with those changes reverted, same results (and tested with no config and default configs), so that's not it. Hopefully I'll have some results later this evening.

**Comment by Lou-Cipher** [comment]
I think this is a bug with how SDL is being used in the master branch.  I've determined it's not specific to a particular version of debian, and have recreated the issue on sid, buster, and stretch.  The reason it was segfaulting immediately on the sid box (my media center) was because of the 12 joysticks connected, one was wedged into the media center in such a way that a button is always pressed.  The issue only occurs when you press a button, then the segfault is immediate.  I've attached output from gdb for both 1.48 and master, both with my modifications for parsing joystick IDs.  1.48 consistently works, master consistently segfaults.

Note that in the data structure taken from master, we get lots of oddities, like weird event types (type = 1539?), implausible joystick IDs (which = 32522?), etc.  I'll have to dig deeper, but this is definitely the source of the segfault, crazy values in the buttons[] array of SDL_Events.

[nestopia_1.48.txt](https://github.com/rdanbrook/nestopia/files/1591856/nestopia_1.48.txt)

[nestopia_master.txt](https://github.com/rdanbrook/nestopia/files/1591859/nestopia_master.txt)

**Comment by Lou-Cipher** [comment]
OK, I checked your fix.  It does work.  And it got me on the right path to dig a little more, so double thanks!  So, the root issue is that on line 965, the call to input_process() is being passed a NULL cNstPads Input::Controllers variable, so on line 439 where cNstPads gets assigned, we'll have to figure out why the new assignment is returning null and/or check for that condition specifically.  I'm digging into it now.

**Comment by Lou-Cipher** [comment]
https://github.com/rdanbrook/nestopia/pull/268

Believe that should be the definitive fix.

**Comment by Lou-Cipher** [comment]
One last update.  My commit history is a bit ugly, I'll see if I can squash it in the morning.

**Comment by Lou-Cipher** [comment]
I've improved the implementation slightly, I think it's more readable and managable than my previous commit.

**Comment by Lou-Cipher** [comment]
So, apparently my git skills need work.  I've created a new PR free of all the madness.  Everything should be working. https://github.com/rdanbrook/nestopia/pull/270

**Comment by rdanbrook** [comment]
I'm pretty sure this issue is resolved, as I can't produce any segfaults.
