### ISSUE TITLE
Nestopia standalone creates new nestopia.xml files every time

### ISSUE THREAD

**Issue by SigmaVirus** [rdanbrook/nestopia#265]
From a fresh installation of Nestopia, start the emulator and configure it to your liking then exit and a nestopia.xml is created in your Nestopia folder which is 100% normal.

Start Nestopia again and launch a FC/FDS/NES game and then exit the emulator, a nestopia.xml should have been created in your games folder all of the sudden.

Start Nestopia yet again and configure where your disksys.rom Famicom Disk System BIOS is present and exit the emulator and a nestopia.xml is created in that folder all of a sudden.

Only way I know of to stop the cluttering of nestopia.xml files everywhere is to configure the emulator once properly and then set the nestopia.xml to read-only.

Nestopia shouldn't create new nestopia.xml files every time you want to configure something or play a game.
One nestopia.xml in the Nestopia folder is more than enough.

**Comment by bunglegrind** [comment]
which OS?

are you using latest binary version (1.48) or have you compiled from sources?

**Comment by SigmaVirus** [comment]
Windows 10 Enterprise LTSB 2016 x64 and latest Nestopia build from [here](http://www.emucr.com/search/label/Nestopia) dated 2017-12-21, however this issue have been present for a while now.

**Comment by rdanbrook** [comment]
The win32 port is considered deprecated and in maintenance mode. It is unmaintainable. If someone is willing to put together a pull request for the nestopia-win32 repo I will accept it though.

The best experience on Windows is through RetroArch, so I recommend using that instead.

**Comment by bunglegrind** [comment]
> Windows 10 Enterprise LTSB 2016 x64 and latest Nestopia build from here dated 2017-12-21, however this issue have been present for a while now.

Since when?

I committed a new feature concerning the configuration files (nestopia.xml, nestopia.log, launcher.xml, netplaylist.xml) merged on september, 25. 

https://github.com/rdanbrook/nestopia-win32/pull/3

Probably it's related.

**Comment by SigmaVirus** [comment]
@rdanbrook 
The Libretro core doesn't have all the options like the standalone does, like writing to .fds disk dumps directly etc.
But thanks anyway.....

@bunglegrind 
For the record I only started testing Nestopia earlier this month because I wanted to clear and clean some .fds dumps I made, I think Nestopia is the only emulator which let's you do that.
And when I saw the application started to create nestopia.xml files in all sorts of folders I thought it would be nice to report the issue but it looks like it was all in wein.

Anyway if you don't care then that's just fine, I can clear and clean my .fds disk dumps anyway so thank you for that!

**Comment by rdanbrook** [comment]
@SigmaVirus thanks for pointing that out, my goal is to implement all features in the libretro port as it will eventually be the only port. I will have to add that to my todo list.

**Comment by bunglegrind** [comment]
I will take a look in the next days. I dislike the idea to have introduced a bug...

**Comment by SigmaVirus** [comment]
@rdanbrook 
Yeah the Libretro port is a pretty solid core these days but it currently lacks a few important features, the ability to write to .fds disk dumps directly of course which I already mentioned but also the ability to fiddle with DIP switches (Nintendo World Championships comes to mind)

But thank you, I appreciate your dedicated work!

@bunglegrind 
I really appreciate that, I wish you good luck!

**Comment by bunglegrind** [comment]
I confirm, the issue was introduced with my contribution...

While I'm trying to figure out how to fix it (yes, nestopia-win it's a mess), I can suggest you to:

- use latest stable version (from http://0ldsk00l.ca/nestopia/ )

or

- use (if you need, of course) the -lua switch at the command line which purpose is to store all the confs file under %APPDATA% (that was my original contribution), if it's fine for your environment work.

**Comment by SigmaVirus** [comment]
I appreciate your dedication @bunglegrind and it's a shame that the nestopia-win32 is pretty much dead these days.

However I'm glad I could at least find a recent build and use the emulator with the functions I needed at the time.
Despite being old and deprecated, Nestopia standalone is a invaluable tool which I will keep in my software toolbox!

**Comment by bunglegrind** [comment]
Fixed (hopefully).

Anyway, you should wait for rdabrook that merges the correction. 

Then, let me know if the  issue still reappears.

**Comment by rdanbrook** [comment]
Thanks for taking the time to do this very tedious work :)
