### ISSUE TITLE
Controller Issues

### ISSUE THREAD

**Issue by shinra358** [rdanbrook/nestopia#79]
Plugging the controller up, or turning on bluetooth after the emulator has already started, results in current controller configuration being deleted and the controller not functioning until you restart the emu with the controller already plugged in or activated and then redoing the configuration. This is part of the hotplugging support. Please fix.

**Comment by SwinglesMan** [comment]
http://cdn.meme.am/instances/58388604.jpg

**Comment by rdanbrook** [comment]
SwinglesMan: Yeah, this is what happens when you work full-time and are also a part-time student. I'm open to pull requests! :)

**Comment by SwinglesMan** [comment]
lol. unfortunately I don't know what 'pull request' means :P
