### ISSUE TITLE
Inconsistencies in audio suspension when clicking on menu bar

### ISSUE THREAD

**Issue by koitsu** [rdanbrook/nestopia#88]
This issue may be specific to Windows platforms, not sure.  I'm testing on Windows XP Pro SP3. The issue is 100% reproducible and indicates a small design/logic mistake within (possibly) the relevant Win32 message handling code which handles WM_LBUTTONDOWN events when clicking within the menu bar (File/Machine/etc.).  Step-by-step:

1. Launch Nestopia
2. Open a game, and ensure music is actively playing
3. Left-click in the blank area of the menu bar to the right of File/Machine/Netplay/View/Options/Help
4. The music (some part of the audio engine?) will briefly stop then resume

The bug: audio should not pause when this area of the menu bar is clicked.

Note: the audio pausing/stopping when File/Machine/Netplay/View/Options/Help are clicked/expanded is proper behaviour (I'm so glad this is one of a few emulators which does this correctly!), so my guess is that some part of the surrounding UI logic there is slightly incorrect.

I'm sorry I don't have a patch :(

**Comment by rdanbrook** [comment]
Closing because I've decided to deprecate the Windows legacy release.
