### ISSUE TITLE
Libretro Core having issues with Soft Patching

### ISSUE THREAD

**Issue by bserafm** [rdanbrook/nestopia#90]
A certain quantity of Rom Translations that use Mapper 23 (mostly Konami games like Kid Dracula and Ganbare Goemon 2), among other ones, aren't playable on the Nestopia core right now, even though they work on Standalone. As far as I understand, it has to do with the Database file and CRC/Sha1 checksum being needed. However, Standalone Nestopia has an option to use soft patches and Bypass the CRC checks, which lets the game work properly. Libretro can use soft patches, but it can't bypass the CRC validation. Maybe that could be added as a core option?

**Comment by rdanbrook** [comment]
Taking care of this with NES 2.0.
