### ISSUE TITLE
 graphic bug of Saint Seiya - Ougon Densetsu Kanketsu Hen (J)

### ISSUE THREAD

**Issue by yuya495** [rdanbrook/nestopia#93]
got these graphic after using second skill of siryuu.

https://www.youtube.com/watch?v=Mbk4yeMyPfQ

**Comment by dragon2snow** [comment]
not have this problem version ?1.2?

**Comment by dragon2snow** [comment]
Where is everyone?@yuya495

**Comment by yuya495** [comment]
Oh! Thank you nestopiaUE developers
Saint Seiya - graphic bug Ougon Densetsu Kanketsu Hen (J) is
I was healed in EmuCR-Nestopia-20151014git
It is I want to close this problem because
